/**
 * Todo OPERATIONS (Suluk registry: `todo`) — the module's functions, each a self-contained sulukts `op`: the CONTRACT + impl
 * that can't be inferred, and NOTHING that can. An op runs DIRECTLY over the base `Db` service (`Effect.flatMap(Db, (db) => …)`,
 * `R = Db`) — no separate `Context.Tag` "service" to wrap. Each op declares its access `roles`, its request `input`, its
 * response `wrap` (the envelope), its `cost`, and its `errors`; the DOMAIN type is INFERRED from the Effect (no `output`), and
 * the ROUTE (`todo.routes.ts`) owns the HTTP identity — `method`/`path`/`name`/`summary` — so those live where the endpoint is
 * mounted, NOT here. `errors` DRIVES the Effect's error channel (the run may fail only with a declared class), so the typed 404
 * bubbles into the static doc with full detail AND can't drift from what the op actually yields.
 *
 * `todo.routes.ts` MOUNTS these ops (`effectPipeRoute({ method, path, …, pipeline: pipeline(getTodo) })`) and COMPOSES them
 * (`all(getTodo, countTodos)` → `{ todo, count }`), bubbling the whole contract up. Every query is owner-scoped (`owned`): a
 * caller only ever reads/mutates their OWN rows (the route injects the AUTHENTICATED principal as `ctx.userId`, never a
 * client-supplied id). Timestamps are stored as `Date`, returned as epoch-ms.
 */
import { Effect } from "effect";
import { z } from "zod";
import { and, desc, eq } from "drizzle-orm";
import { op, envelope, listEnvelope, fixedEnvelope, NotFoundError, type CostModel } from "@suluk/effect";
import { Db } from "../app";
import { todo, TodoItemSchema, CreateReq, UpdateReq, type TodoRow, type TodoItem } from "../db/todo";

/** Project a stored row (Date timestamps) to the wire DTO (epoch-ms). */
const toItem = (r: TodoRow): TodoItem => ({
  id: r.id,
  userId: r.userId,
  title: r.title,
  completed: r.completed,
  createdAt: r.createdAt.getTime(),
  updatedAt: r.updatedAt.getTime(),
});
/** the owner-scoping predicate reused by every by-id op — a caller can only ever touch a row where BOTH the id AND owner match. */
const owned = (userId: string, id: string) => and(eq(todo.id, id), eq(todo.userId, userId));

// the two entity envelopes (built once so the doc + render can't drift) + per-op COST (summed up the tree by effectPipeRoute).
const one = envelope("todo", TodoItemSchema);
const many = listEnvelope("todos", TodoItemSchema, { describe: "The caller's todos, newest first." });
const readCost: CostModel = { components: [], infra: { "d1.read": 1 }, settlement: { method: "rate-limited" } };
const writeCost: CostModel = { components: [], infra: { "d1.write": 1, "d1.read": 1 }, settlement: { method: "rate-limited", overflow: "credit" } };
const deleteCost: CostModel = { components: [], infra: { "d1.write": 1 }, settlement: { method: "rate-limited", overflow: "credit" } };
// shared by every standalone op: the audience (→ scope/rate-limit-key/401/userId) + the doc tag.
const base = { roles: ["signed-in"] as const, tags: ["Todos"] };

/** the caller's own todos, newest first → `{ todos }`. (Mounted GET /api/todos in `todo.routes.ts`.) */
export const listTodos = op({
  ...base, wrap: many, cost: readCost,
  run: (ctx) => Effect.flatMap(Db, (db) => Effect.promise(async () =>
    (await db.select().from(todo).where(eq(todo.userId, ctx.userId)).orderBy(desc(todo.createdAt))).map(toItem))),
});

/** one todo the caller OWNS → `{ todo }`; a non-owned/absent id → typed 404. `errors: [NotFoundError]` DRIVES the run's error
 *  channel (the run may fail ONLY with a listed class) — so the 404 bubbles into the doc with full detail AND can't drift. */
export const getTodo = op({
  ...base, wrap: one, errors: [NotFoundError], cost: readCost,
  run: (ctx) => Effect.flatMap(Db, (db) => Effect.gen(function* () {
    const [row] = yield* Effect.promise(() => db.select().from(todo).where(owned(ctx.userId, ctx.param("id")!)).limit(1));
    if (!row) return yield* new NotFoundError({ resource: "todo", id: ctx.param("id")! });
    return toItem(row);
  })),
});

/** (composed-only — NO standalone route) the caller's total todo count; fans in with `getTodo` in the `getTodoDetail` `all`. */
export const countTodos = op({
  wrap: envelope("count", z.number().int().describe("How many todos the caller has.")), cost: readCost,
  run: (ctx) => Effect.flatMap(Db, (db) => Effect.promise(async () =>
    (await db.select({ id: todo.id }).from(todo).where(eq(todo.userId, ctx.userId))).length)),
});

/** create a todo owned by the caller → 201 `{ todo }`. (Mounted POST /api/todos.) */
export const createTodo = op({
  ...base, validateBody: true, input: CreateReq, wrap: one, status: 201, cost: writeCost,
  run: (ctx, body: { title: string }) => Effect.flatMap(Db, (db) => Effect.promise(async () => {
    // the `id` is generated by the column's `$defaultFn(() => nanoid())`; omit it here and read the stored row back.
    const now = new Date();
    const [row] = await db.insert(todo).values({ userId: ctx.userId, title: body.title, completed: false, createdAt: now, updatedAt: now }).returning();
    return toItem(row);
  })),
});

/** patch a todo the caller OWNS → `{ todo }`; absent/non-owned → 404. */
export const updateTodo = op({
  ...base, validateBody: true, input: UpdateReq, wrap: one, errors: [NotFoundError], cost: writeCost,
  run: (ctx, patch: { title?: string; completed?: boolean }) => Effect.flatMap(Db, (db) => Effect.gen(function* () {
    const rows = yield* Effect.promise(() => db.update(todo).set({ ...patch, updatedAt: new Date() }).where(owned(ctx.userId, ctx.param("id")!)).returning());
    if (!rows[0]) return yield* new NotFoundError({ resource: "todo", id: ctx.param("id")! });
    return toItem(rows[0]);
  })),
});

/** delete a todo the caller OWNS → 200 `{ deleted:true }`; absent/non-owned → 404. No `status`: effectPipeRoute defaults a
 *  body-carrying wrap on a no-body method (DELETE→204) to 200, so the confirmation renders. */
export const deleteTodo = op({
  ...base,
  wrap: fixedEnvelope<void, { deleted: true }>(z.object({ deleted: z.literal(true) }).describe("The todo was deleted."), { deleted: true }),
  errors: [NotFoundError], cost: deleteCost,
  run: (ctx) => Effect.flatMap(Db, (db) => Effect.gen(function* () {
    const rows = yield* Effect.promise(() => db.delete(todo).where(owned(ctx.userId, ctx.param("id")!)).returning({ id: todo.id }));
    if (rows.length === 0) return yield* new NotFoundError({ resource: "todo", id: ctx.param("id")! });
  })),
});
