/**
 * Todo MODELS (Suluk registry: `todo`) — the MODEL layer of the controller→service→model split: db-query `sulukFn`s, each the
 * LEAF that runs a query over the base `Db` and carries the STATE-SOURCE facts on its slice — the entity response schema (the
 * master `todo.zodSchema`, so the db schema IS the response type, with its constraints + `$ref` provenance), its `cost` (DEFINED
 * HERE, so it bubbles up), and any by-id `errors` (`[NotFoundError]`). A SERVICE `sulukFmt`s these; a ROUTE `sulukFmt`s the
 * services — and because every fact lives here, nothing upstream restates cost/errors/schema. Every query is owner-scoped
 * (`owned`); timestamps are epoch-ms integers, so a returned ROW is already the wire shape — no Date↔number mapping.
 */
import { Effect } from "effect";
import { z } from "zod";
import { and, desc, eq } from "drizzle-orm";
import { sulukFn, NotFoundError, type CostModel } from "@suluk/effect";
import { Db } from "../app";
import { todo } from "../db/todo";

/** A todo row AS RETURNED — inferred from the master; timestamps are epoch-ms `number`s, so the row IS the wire item. */
export type TodoRow = z.infer<typeof todo.zodSchema>;
export type TodoItem = TodoRow;
/** the entity response schema — the master itself (no wire projection: the columns already carry the wire types). */
export const TodoItemSchema = todo.zodSchema;
/** request bodies — SLICED off the master so a column's `.trim().min(1).max(500).regex(…)` validates on the wire. */
export const CreateReq = todo.zodSchema.pick({ title: true });
export const UpdateReq = todo.zodSchema.pick({ title: true, completed: true }).partial();

/** the owner-scoping predicate every by-id query reuses — a caller can only ever touch a row where BOTH id AND owner match. */
const owned = (userId: string, id: string) => and(eq(todo.id, id), eq(todo.userId, userId));

// The per-operation COSTS — DEFINED on the models; `sulukFmt` SUMS them up the tree so services/routes declare none.
const readCost: CostModel = { components: [], infra: { "d1.read": 1 }, settlement: { method: "rate-limited" } };
const writeCost: CostModel = { components: [], infra: { "d1.write": 1, "d1.read": 1 }, settlement: { method: "rate-limited", overflow: "credit" } };
const deleteCost: CostModel = { components: [], infra: { "d1.write": 1 }, settlement: { method: "rate-limited", overflow: "credit" } };

/** one todo the caller OWNS by id → `TodoItem`; a non-owned/absent id → typed 404 (declared here, where it is thrown). */
export const findTodo = sulukFn({
  cost: readCost, errors: [NotFoundError], ok: { schema: TodoItemSchema },
  step: { role: "given", text: "a todo the caller owns exists" },
  run: (ctx, id: string) => Effect.flatMap(Db, (db) => Effect.gen(function* () {
    const [row] = yield* Effect.promise(() => db.select().from(todo).where(owned(ctx.userId, id)).limit(1));
    if (!row) return yield* new NotFoundError({ resource: "todo", id });
    return row; // already the wire item (epoch-ms timestamps)
  })),
});

/** the caller's own todos, newest first → `TodoItem[]` (a `listView` arrays the entity schema at the route). */
export const listTodos = sulukFn({
  cost: readCost, ok: { schema: TodoItemSchema },
  run: (ctx): Effect.Effect<TodoItem[], never, Db> => Effect.flatMap(Db, (db) => Effect.promise(() =>
    db.select().from(todo).where(eq(todo.userId, ctx.userId)).orderBy(desc(todo.createdAt)))),
});

/** create a todo owned by the caller → `TodoItem`. The `id` is generated by the column's `$defaultFn(() => nanoid())`. */
export const insertTodo = sulukFn({
  cost: writeCost, ok: { schema: TodoItemSchema },
  run: (ctx, body: { title: string }) => Effect.flatMap(Db, (db) => Effect.promise(async () => {
    const now = Date.now();
    const [row] = await db.insert(todo).values({ userId: ctx.userId, title: body.title, completed: false, createdAt: now, updatedAt: now }).returning();
    return row;
  })),
});

/** patch a todo the caller OWNS → `TodoItem`; absent/non-owned → 404. Takes `{ id, patch }` (the route supplies the id). */
export const patchTodo = sulukFn({
  cost: writeCost, errors: [NotFoundError], ok: { schema: TodoItemSchema },
  step: { role: "given", text: "a todo the caller owns exists" },
  run: (ctx, { id, patch }: { id: string; patch: { title?: string; completed?: boolean } }) =>
    Effect.flatMap(Db, (db) => Effect.gen(function* () {
      const rows = yield* Effect.promise(() => db.update(todo).set({ ...patch, updatedAt: Date.now() }).where(owned(ctx.userId, id)).returning());
      if (!rows[0]) return yield* new NotFoundError({ resource: "todo", id });
      return rows[0];
    })),
});

/** delete a todo the caller OWNS → void; absent/non-owned → 404. The route's service maps the void to `{ deleted: true }`. */
export const dropTodo = sulukFn({
  cost: deleteCost, errors: [NotFoundError],
  step: { role: "given", text: "a todo the caller owns exists" },
  run: (ctx, id: string): Effect.Effect<void, InstanceType<typeof NotFoundError>, Db> =>
    Effect.flatMap(Db, (db) => Effect.gen(function* () {
      const rows = yield* Effect.promise(() => db.delete(todo).where(owned(ctx.userId, id)).returning({ id: todo.id }));
      if (rows.length === 0) return yield* new NotFoundError({ resource: "todo", id });
    })),
});

/** the caller's total todo count → `number` (its OWN schema, not the entity) — fans in with `findTodo` in `getTodoDetail`. */
export const countTodos = sulukFn({
  cost: readCost, ok: { schema: z.number().int().describe("How many todos the caller has.") },
  run: (ctx): Effect.Effect<number, never, Db> => Effect.flatMap(Db, (db) => Effect.promise(async () =>
    (await db.select({ id: todo.id }).from(todo).where(eq(todo.userId, ctx.userId))).length)),
});
