/**
 * Todo MODELS (Suluk registry: `todo`) — the MODEL layer of the controller→service→model split. Each is built from ONE query
 * via `queryOne`/`queryMany` (from `../app`): the query is the SINGLE source — its PROJECTION derives the response `ok.schema`
 * at build time (no hand-written `TodoItemSchema`), and the same query runs per-request. Each carries the STATE-SOURCE facts on
 * its slice — the derived schema, its `cost` (DEFINED HERE, so it bubbles up the sulukFmt pipeline), its by-id `errors`, and its
 * BDD `step`. Every query is owner-scoped (`owned`); timestamps are epoch-ms integers, so a returned ROW is already the wire item.
 */
import { Effect } from "effect";
import { z } from "zod";
import { and, desc, eq } from "drizzle-orm";
import { sulukFn, NotFoundError, type CostModel } from "@suluk/effect";
import { Db, queryOne, queryMany, mutate } from "../app";
import { todo } from "../db/todo";

/** A todo row AS RETURNED — inferred from the master; timestamps are epoch-ms `number`s, so the row IS the wire item. */
export type TodoRow = z.infer<typeof todo.zodSchema>;
export type TodoItem = TodoRow;
/** the entity schema — the master itself; used by the composite `getTodoDetail` route (the CRUD models DERIVE theirs). */
export const TodoItemSchema = todo.zodSchema;
/** request bodies — SLICED off the master so a column's `.trim().min(1).max(500).regex(…)` validates on the wire. */
export const CreateReq = todo.zodSchema.pick({ title: true });
export const UpdateReq = todo.zodSchema.pick({ title: true, completed: true }).partial();

/** the owner-scoping predicate every by-id query reuses — a caller can only ever touch a row where BOTH id AND owner match. */
const owned = (userId: string, id: string) => and(eq(todo.id, id), eq(todo.userId, userId));

// The per-operation COSTS — DEFINED on the models; `sulukFmt` SUMS them up the tree so services/routes declare none.
const readCost: CostModel = { components: [], infra: { "d1.read": 1 }, settlement: { method: "rate-limited" } };
const writeCost: CostModel = { components: [], infra: { "d1.write": 1, "d1.read": 1 }, settlement: { method: "rate-limited", overflow: "credit" } };
const deleteCost: CostModel = { components: [], infra: { "d1.write": 1 }, settlement: { method: "rate-limited", overflow: "credit" } };

/** one todo the caller OWNS by id → `TodoItem`; a non-owned/absent id → typed 404. `ok.schema` DERIVES from the select, the
 *  404 DERIVES from `orElse` — neither is restated. */
export const findTodo = queryOne({
  cost: readCost, step: { role: "given", text: "a todo the caller owns exists" },
  query: (db, ctx, id: string) => db.select().from(todo).where(owned(ctx.userId, id)).limit(1),
  orElse: (_ctx, id) => new NotFoundError({ resource: "todo", id }),
});

/** the caller's own todos, newest first → `TodoItem[]`; the route's `listView` arrays the derived item schema. */
export const listTodos = queryMany({
  cost: readCost,
  query: (db, ctx) => db.select().from(todo).where(eq(todo.userId, ctx.userId)).orderBy(desc(todo.createdAt)),
});

/** create a todo owned by the caller → `TodoItem`. `input` is SLICED off the master (`CreateReq`) — it TYPES `body` AND becomes
 *  the request body (validated + bubbled up), so the create route restates nothing. The `id` is generated by `$defaultFn(nanoid)`. */
export const insertTodo = queryOne({
  cost: writeCost,
  input: CreateReq, // = todo.zodSchema.pick({ title: true }) — body is inferred as { title: string }
  query: (db, ctx, body) => {
    const now = Date.now();
    return db.insert(todo).values({ userId: ctx.userId, title: body.title, completed: false, createdAt: now, updatedAt: now }).returning();
  },
});

/** patch a todo the caller OWNS → `TodoItem`; absent/non-owned → 404 (from `orElse`). Takes `{ id, patch }`. */
export const patchTodo = queryOne({
  cost: writeCost, step: { role: "given", text: "a todo the caller owns exists" },
  query: (db, ctx, { id, patch }: { id: string; patch: { title?: string; completed?: boolean } }) =>
    db.update(todo).set({ ...patch, updatedAt: Date.now() }).where(owned(ctx.userId, id)).returning(),
  orElse: (_ctx, { id }) => new NotFoundError({ resource: "todo", id }),
});

/** delete a todo the caller OWNS → void; absent/non-owned → 404 (from `orElse`, which is the SINGLE place the error is
 *  defined + the source the doc reads). The route's service maps the void to `{ deleted: true }`. */
export const dropTodo = mutate({
  cost: deleteCost, step: { role: "given", text: "a todo the caller owns exists" },
  query: (db, ctx, id: string) => db.delete(todo).where(owned(ctx.userId, id)).returning({ id: todo.id }),
  orElse: (_ctx, id) => new NotFoundError({ resource: "todo", id }),
});

/** the caller's total todo count → `number` (an aggregate, not a row projection) — fans in with `findTodo` in `getTodoDetail`. */
export const countTodos = sulukFn({
  cost: readCost, ok: { schema: z.number().int().describe("How many todos the caller has.") },
  run: (ctx): Effect.Effect<number, never, Db> => Effect.flatMap(Db, (db) => Effect.promise(async () =>
    (await db.select({ id: todo.id }).from(todo).where(eq(todo.userId, ctx.userId))).length)),
});
