/**
 * projectNodeAgent (C034) — the SECOND agent-runtime adapter, alongside `projectCloudflareAgent`. It exists to keep the
 * runtime SEAM honest: a real, non-Cloudflare runtime with a DIFFERENT deploy shape (a long-lived Bun/Node process, NO
 * Durable Objects) projected from the SAME contract, reusing the SAME tool derivation (`runtime-shared`). One declaration
 * → an OWNED Bun-served agent loop. The bespoke brain (model / system prompt / loop policy / each tool's `execute`) is
 * left as marked TODOs, exactly like the Cloudflare adapter — only the host wrapper differs (Bun.serve vs an AIChatAgent
 * Durable Object). L3-pure: source strings, no runtime dep, deterministic, fail-loud.
 *
 * v1 scaffolds the NAMED agent only (recursive sub-agent scaffolding is the Cloudflare adapter's; not yet mirrored here).
 */
import type { OpenAPIv4Document, SulukSkillRef } from "@suluk/core";
import { agentMap, resolveInstruction } from "./resolve";
import { reachableSurface, residentSurface } from "./conformance";
import { assertAgentInstallable } from "./lint";
import { contentHash } from "./skill";
import { pascal, primarySkill, toolsConst } from "./runtime-shared";

export interface NodeAgentOptions {
  /** the exported server/agent name (default: PascalCase of the agent name). Used only in a comment + the file name. */
  name?: string;
  /** pinned snapshots keyed `"<agent>/<skill>"` (preferred) or bare `"<skill>"`; the primary skill's text is the system prompt. */
  instructions?: Record<string, string>;
  /** an MCP endpoint the tool `execute` stubs can dispatch to — referenced in a comment, never embedded as a credential. */
  mcpUrl?: string;
  /** the port the generated `Bun.serve` listens on (default 8787). */
  port?: number;
}

export interface NodeAgentArtifacts {
  /** path → owned source the user writes into their Node/Bun project. */
  files: Record<string, string>;
  /** reachable sub-agents (NOT scaffolded by this v1 adapter — see Cloudflare's recursive version). */
  reachableSubAgents: string[];
}

function serverFile(doc: OpenAPIv4Document, agentName: string, name: string, opts: NodeAgentOptions): string {
  const agent = agentMap(doc)[agentName]!;
  const routes = (agent.routes ?? {}) as Record<string, { operationRef: string; tier?: string }>;
  const resident = residentSurface(doc, agentName);
  const coldTail = Object.keys(routes).filter((k) => routes[k]!.tier === "cold-tail");
  const [primName, primSkill] = primarySkill(agent.skills) ?? [undefined, undefined as SulukSkillRef | undefined];
  const model = primSkill?.model?.[0];
  const snapshot = primName ? resolveInstruction(opts.instructions, agentName, primName) : undefined;
  // value + comment kept separate so the statement terminator precedes the comment (a `const X = v // c;` puts `;` in the comment).
  const systemValue = snapshot !== undefined ? JSON.stringify(snapshot) : `"TODO: your system prompt"`;
  const systemComment = snapshot !== undefined
    ? `pinned from skill "${primName}" (contentHash ${contentHash(snapshot)})`
    : `pin from ${primSkill?.provenance?.source ?? `skill "${primName ?? "—"}"`}`;

  return `// CANDIDATE — generated by @suluk/agents projectNodeAgent (${name}). OWNED SOURCE you complete.
// A long-lived Bun server hosting the agent loop — NO Durable Objects (a plain process). DERIVED from the contract:
// the tools (name/description/inputSchema + approval gates). YOURS: the model, system prompt, loop policy, execute bodies.
import { streamText, tool, jsonSchema, stepCountIs } from "ai";
import { openai } from "@ai-sdk/openai"; // TODO: or your provider (@ai-sdk/anthropic, ollama-ai-provider, …)

const SYSTEM = ${systemValue}; // ${systemComment}

Bun.serve({
  port: ${opts.port ?? 8787},
  async fetch(req) {
    if (req.method !== "POST") return new Response("POST a JSON { messages: ModelMessage[] } body", { status: 405 });
    const { messages } = await req.json(); // expects ai-SDK ModelMessage[] (convert your transport's shape first)
    const result = streamText({
      model: openai("gpt-4.1-mini"), // TODO: pick your model${model ? ` — the contract's "${primName}" skill prefers: ${model}` : ""}
      system: SYSTEM,
      messages,
      stopWhen: stepCountIs(5), // TODO (yours): your loop policy
      tools, // resident tools below; lazy-register \`discoverableTools\` (cold-tail) on demand to save context
    });
    return result.toTextStreamResponse();
  },
});

/** RESIDENT tools — DERIVED from the contract. Edit the \`execute\` bodies (the bespoke brain); the schemas are the contract's. */
${toolsConst(doc, "tools", resident, routes, opts.mcpUrl)}
${coldTail.length ? `/** COLD-TAIL tools — kept out of the default surface (C027 tier-trim); register on demand. */\n${toolsConst(doc, "discoverableTools", coldTail, routes, opts.mcpUrl)}` : ""}`;
}

/** Project one agent → an owned Bun/Node agent-server scaffold. Pure, fail-loud. */
export function projectNodeAgent(doc: OpenAPIv4Document, agentName: string, opts: NodeAgentOptions = {}): NodeAgentArtifacts {
  assertAgentInstallable(doc, agentName); // a dangling ref / missing depth fails here, not by emitting a broken scaffold
  const name = opts.name ?? pascal(agentName);
  return {
    files: { "src/server.ts": serverFile(doc, agentName, name, opts) },
    reachableSubAgents: reachableSurface(doc, agentName).agents,
  };
}
