/**
 * generateMoneyTests — PARITY §2 "Checkout & E-commerce Resilience" made an EXECUTABLE, in-process conformance
 * suite over the @suluk/payments pricing primitives (saastarter-parity Phase 0). Unlike the wire conformance suite,
 * the money invariants are properties of the SHARED, app-independent primitives (there is nothing in a v4 document
 * to walk for verifyAmount) — so this is a separate emitter that produces a self-contained `bun test` file an app
 * commits + runs. No network, no app coupling, no document input.
 *
 * Provenance note (honesty, adopt-by-receipt): the anti-tampering + integer-cents + never-over-discount invariants
 * are faithful encodings of saastarter's checkout intent. The exact-sum proration + deterministic-idempotency
 * invariants are STRONGER than saastarter's actual code (PARITY records a real cart/order proration drift bug and
 * an ad-hoc retry path) — they assert what @suluk/payments was authored to GUARANTEE, an origination inspired by the
 * parity goal, not a behavioral port. The generated header says so.
 */

export interface MoneyTestsOptions {
  /** which runner's imports to emit (both share test/expect/describe). Default "bun". */
  framework?: "bun" | "vitest";
  /** the import specifier for the pricing primitives. Default "@suluk/payments". */
  stripeModule?: string;
}

/** Emit the money-correctness conformance suite as a self-contained test-file string. */
export function generateMoneyTests(opts: MoneyTestsOptions = {}): string {
  const importLine = opts.framework === "vitest"
    ? `import { test, expect, describe } from "vitest";`
    : `import { test, expect, describe } from "bun:test";`;
  const mod = opts.stripeModule ?? "@suluk/payments";

  return `/**
 * Checkout money-correctness — CONFORMANCE suite. AUTO-GENERATED by @suluk/testgen. Do not edit.
 *
 * PARITY §2 "Checkout & E-commerce Resilience" made executable over the @suluk/payments pricing primitives — the
 * arithmetic that separates a toy cart from one you'd trust with money. In-process, no network: it asserts the
 * SHARED primitives uphold the invariants, so the cart-drawer total and the order-summary total can never drift.
 *
 * Honesty: the exact-sum proration + deterministic-idempotency checks assert what @suluk/payments GUARANTEES — they
 * are stronger than saastarter's actual impl (which has a known proration-drift bug), an origination inspired by
 * the parity goal rather than a behavioral port.
 *
 * Run: \`bun test\` (requires ${mod}).
 */
${importLine}
import {
  subtotal, computeDiscountAmount, validateDiscount, prorateDiscount, orderTotal, verifyAmount,
  cartFingerprint, idempotencyKey, type CartLine, type Discount,
} from ${JSON.stringify(mod)};

const sum = (ns: number[]) => ns.reduce((a, b) => a + b, 0);

describe("money — anti-tampering (never trust the amount the browser sends)", () => {
  const lines: CartLine[] = [{ unitCents: 1999, qty: 2, id: "a" }, { unitCents: 500, qty: 1, id: "b" }];
  test("verifyAmount accepts the exact recomputed total and rejects a tampered one", () => {
    const expected = orderTotal(lines, null).totalCents; // 4498
    expect(verifyAmount(lines, null, expected).ok).toBe(true);
    const tampered = verifyAmount(lines, null, expected - 100);
    expect(tampered.ok).toBe(false);
    expect(tampered.reason).toBe("amount-mismatch");
  });
});

describe("money — integer cents only, a discount never exceeds the subtotal", () => {
  const lines: CartLine[] = [{ unitCents: 1234, qty: 3 }];
  test("subtotal + total are integers", () => {
    const t = orderTotal(lines, null);
    expect(Number.isInteger(t.subtotalCents)).toBe(true);
    expect(Number.isInteger(t.totalCents)).toBe(true);
  });
  test("a fixed discount larger than the subtotal clamps — the total is never negative", () => {
    const huge: Discount = { type: "fixed", value: 9_999_999 };
    const sub = subtotal(lines);
    expect(computeDiscountAmount(sub, huge)).toBe(sub); // clamped to subtotal
    expect(orderTotal(lines, huge).totalCents).toBe(0); // never below zero
  });
  test("a percent discount is rounded to whole cents and clamped to [0, subtotal]", () => {
    const amt = computeDiscountAmount(1000, { type: "percent", value: 33 });
    expect(amt).toBe(330);
    expect(amt).toBeLessThanOrEqual(1000);
  });
});

describe("money — proration sums EXACTLY to the order discount (cart drawer ⊨ order summary)", () => {
  const carts: CartLine[][] = [
    [{ unitCents: 1999, qty: 2 }, { unitCents: 500, qty: 1 }, { unitCents: 333, qty: 3 }],
    [{ unitCents: 100, qty: 1 }, { unitCents: 100, qty: 1 }, { unitCents: 100, qty: 1 }],
    [{ unitCents: 4500, qty: 1 }],
  ];
  for (let i = 0; i < carts.length; i++) {
    for (const d of [101, 333, 777]) {
      test(\`cart \${i} · discount \${d}¢ prorates to an exact sum, each share within its line\`, () => {
        const lines = carts[i];
        const want = Math.min(d, subtotal(lines));
        const shares = prorateDiscount(lines, want);
        expect(sum(shares)).toBe(want);                       // exact — no lost/created cent
        shares.forEach((s, j) => expect(s).toBeLessThanOrEqual(subtotal([lines[j]])));
      });
    }
  }
});

describe("money — specific discount-rejection reasons (tell the shopper WHY)", () => {
  test("no-discount / non-positive-value / percent-out-of-range / below-minimum", () => {
    expect(validateDiscount(1000, null).reason).toBe("no-discount");
    expect(validateDiscount(1000, { type: "fixed", value: 0 }).reason).toBe("non-positive-value");
    expect(validateDiscount(1000, { type: "percent", value: 150 }).reason).toBe("percent-out-of-range");
    expect(validateDiscount(500, { type: "fixed", value: 100, minSubtotalCents: 1000 }).reason).toBe("below-minimum");
    expect(validateDiscount(2000, { type: "percent", value: 10 }).valid).toBe(true);
  });
});

describe("money — deterministic idempotency (a retry reuses one payment intent, never double-charges)", () => {
  const lines: CartLine[] = [{ unitCents: 1999, qty: 2, id: "a" }, { unitCents: 500, qty: 1, id: "b" }];
  test("same cart + scope ⇒ same key; a changed cart ⇒ a different key", () => {
    const k1 = idempotencyKey("user_1", lines);
    expect(idempotencyKey("user_1", [...lines].reverse())).toBe(k1); // order-independent — same charge
    expect(idempotencyKey("user_1", [{ unitCents: 1999, qty: 3, id: "a" }, { unitCents: 500, qty: 1, id: "b" }])).not.toBe(k1);
    expect(idempotencyKey("user_2", lines)).not.toBe(k1);            // a different principal is a different attempt
    expect(cartFingerprint(lines)).toBe(cartFingerprint([...lines].reverse()));
  });
});
`;
}
