/**
 * The generated app's LOCAL, on-push CI/CD (modeled on toolfactory — "own the wiring, zero external-CI cost"). On push a
 * git hook returns instantly and DETACHES a background pipeline that runs the idempotent stages in an ISOLATED git
 * worktree (never blocking the push or the working tree) and, when the pushed ref is the default branch, deploys via the
 * `@suluk/deploy` API (credentials from the decrypted `.env` — no wrangler). Verdicts are recorded as local git tags.
 * These emitters are PURE string-builders (like the others in plan.ts); `generate.ts` writes them.
 */

/** `.githooks/pre-push` — async, non-blocking. Installed by the package.json `prepare` (git config core.hooksPath .githooks). */
export function buildPrePushHook(): string {
  return `#!/usr/bin/env bash
# AUTO-GENERATED by @suluk/platform — ASYNC local CI/CD. Returns INSTANTLY (never gates the push or your working tree) and
# launches a DETACHED background pipeline (scripts/ci-run.ts) that runs the checks/tests in an ISOLATED git worktree and,
# on the default branch, deploys. Verdicts are local git tags + .ci/<sha>.log. Bypass entirely: git push --no-verify.
set -euo pipefail
[ -n "\${SULUK_CI:-}" ] && exit 0   # don't recurse if a background deploy ever pushes

PLAN="$(cat || true)"               # git feeds the push plan on stdin: "<localref> <localsha> <remoteref> <remotesha>"
REPO="$(git rev-parse --show-toplevel)"
SHA="$(git rev-parse HEAD)"

DEPLOY=0                            # deploy ONLY when pushing the default branch
while read -r _l _ls rref _rs; do
  case "\${rref:-}" in refs/heads/main | refs/heads/master) DEPLOY=1 ;; esac
done <<<"$PLAN"

mkdir -p "$REPO/.ci"
LOG="$REPO/.ci/\${SHA}.log"
# Fully detach (setsid → new session) so it survives git + this hook exiting. Hook returns now → the push proceeds.
setsid env SULUK_CI=1 bun "$REPO/scripts/ci-run.ts" "$SHA" "$DEPLOY" >"$LOG" 2>&1 </dev/null &

echo "⚡ Suluk CI launched in background for \${SHA:0:7} (deploy=$DEPLOY)"
echo "   log:     .ci/\${SHA:0:7}.log"
echo "   verdict: git tag -l 'ci/\${SHA:0:7}/*'"
exit 0
`;
}

/** `scripts/ci-stages.ts` — the ONE ordered, idempotent, fail-fast stage list, shared by ci-run.ts (worktree) + ci-local.ts. */
export function buildCiStages(services: string[]): string {
  const sulukGate = services.includes("audit") && services.includes("contract");
  const stages = [
    `  { label: "format", cmd: ["bun", "run", "format:check"] },     // prettier --check — no writes`,
    `  { label: "lint", cmd: ["bun", "run", "lint"] },               // eslint`,
    `  { label: "typecheck", cmd: ["bun", "run", "typecheck"] },     // tsc --noEmit`,
    ...(sulukGate ? [`  { label: "suluk-gate", cmd: ["bun", "run", "suluk:gate"] },   // the unified conformance gate (@suluk/cockpit + @suluk/harden)`] : []),
    `  { label: "bundle", cmd: ["bun", "run", "bundle:check"] },     // the Worker bundles (same Bun.build the deploy runs)`,
    `  { label: "test", cmd: ["bun", "test"] },`,
  ].join("\n");
  return `// AUTO-GENERATED by @suluk/platform — the ONE ordered CI stage list, shared by scripts/ci-run.ts (async/worktree/deploy)
// and scripts/ci-local.ts (in-place \`bun run ci:local\`) so they can NEVER drift. Ordered cheap→expensive to fail fast.
// Every stage is IDEMPOTENT: it reads/checks only (format:check doesn't write; bundle:check builds to the gitignored .ci/;
// test/typecheck/lint mutate nothing) — run it twice → identical result. Deploy is NOT a stage (ci-run runs it after all pass).
export interface Stage {
  label: string;
  cmd: string[];
}

export const STAGES: readonly Stage[] = [
${stages}
];
`;
}

/** `scripts/ci-run.ts` — the detached runner: isolated worktree → STAGES → deploy (default branch) → git-tag verdicts → cleanup. */
export function buildCiRun(): string {
  return `#!/usr/bin/env bun
/**
 * AUTO-GENERATED by @suluk/platform — the DETACHED CI runner launched by .githooks/pre-push (the hook returns instantly).
 * Runs the pipeline in an ISOLATED git worktree at the pushed commit, so it never touches your working tree — safe to run
 * async while you keep editing. Flow: worktree add → STAGES (fail-fast) → deploy (if the default branch) → tags → cleanup.
 * Progress is recorded as LOCAL git tags: ci/<sha>/started · ok-<stage> · failed-<stage> · deployed · passed|failed.
 * Logs: .ci/<sha>.log.  Inspect: \`git tag -l 'ci/<sha7>/*'\`.
 */
import { spawnSync } from "node:child_process";
import { mkdirSync, symlinkSync, rmSync } from "node:fs";

const [sha = "", deployFlag = "0"] = process.argv.slice(2);
const deploy = deployFlag === "1";
const short = sha.slice(0, 7);
const run = (cmd: string, args: string[], opts: Parameters<typeof spawnSync>[2] = {}) => spawnSync(cmd, args, { encoding: "utf8", ...opts });
const repo = run("git", ["rev-parse", "--show-toplevel"]).stdout.trim();
const tag = (name: string) => run("git", ["tag", "-f", \`ci/\${short}/\${name}\`, sha], { cwd: repo });

const wt = \`\${process.env.TMPDIR ?? "/tmp"}/suluk-ci-\${short}-\${Date.now()}\`;
mkdirSync(\`\${repo}/.ci\`, { recursive: true });
console.log(\`──── Suluk CI \${short} (deploy=\${deploy}) ────\`);
tag("started");

const cleanup = () => { run("git", ["worktree", "remove", "--force", wt], { cwd: repo }); run("git", ["worktree", "prune"], { cwd: repo }); };
process.on("exit", cleanup);

if (run("git", ["worktree", "add", "--detach", wt, sha], { cwd: repo, stdio: "inherit" }).status !== 0) {
  tag("failed-worktree"); tag("failed"); process.exit(1);
}
// Reuse the dev tree's installed deps (no reinstall per push); @suluk/env reads the real repo's key via SULUK_PROJECT_DIR.
try { rmSync(\`\${wt}/node_modules\`, { recursive: true, force: true }); symlinkSync(\`\${repo}/node_modules\`, \`\${wt}/node_modules\`); } catch {}
const childEnv = { ...process.env, SULUK_PROJECT_DIR: repo, SULUK_CI: "1" };

// The pipeline lives in scripts/ci-stages.ts (shared with \`bun run ci:local\`) so the two can't drift.
const { STAGES } = await import(\`\${wt}/scripts/ci-stages.ts\`);
let ok = true;
for (const { label, cmd } of STAGES as { label: string; cmd: string[] }[]) {
  console.log(\`\\n── \${label} ──\`);
  const r = run(cmd[0] ?? "", cmd.slice(1), { cwd: wt, stdio: "inherit", env: childEnv });
  if (r.status !== 0) { tag(\`failed-\${label}\`); ok = false; break; }
  tag(\`ok-\${label}\`);
}

if (ok && deploy) {
  console.log("\\n── deploy ──");
  const r = run("bun", ["run", "deploy"], { cwd: wt, stdio: "inherit", env: childEnv });
  if (r.status === 0) tag("deployed"); else { tag("deploy-failed"); ok = false; }
}

tag(ok ? "passed" : "failed");
console.log(ok ? "\\n✅ CI passed" : "\\n❌ CI failed");
process.exit(ok ? 0 : 1);
`;
}

/** `scripts/ci-local.ts` — the in-place synchronous variant (`bun run ci:local`); same STAGES, no worktree/tags/deploy. */
export function buildCiLocal(): string {
  return `#!/usr/bin/env bun
// AUTO-GENERATED by @suluk/platform — run the full CI pipeline (scripts/ci-stages.ts) IN-PLACE: the local equivalent of the
// async pre-push CI, minus the worktree / tags / deploy. Same ordered, fail-fast, idempotent stages. \`bun run ci:local\`
import { spawnSync } from "node:child_process";
import { STAGES } from "./ci-stages";

console.log(\`──── Suluk CI (local · \${STAGES.length} stages) ────\`);
for (const s of STAGES) {
  console.log(\`\\n── \${s.label} ──\`);
  const r = spawnSync(s.cmd[0] ?? "", s.cmd.slice(1), { stdio: "inherit" });
  if (r.status !== 0) { console.error(\`\\n✗ CI failed at stage: \${s.label}\`); process.exit(r.status ?? 1); }
}
console.log("\\n✅ CI passed — all stages green.");
`;
}

/** `scripts/ci-worktree.ts` — manually launch the detached worktree CI on any ref (`bun run ci:worktree [ref] [--deploy]`). */
export function buildCiWorktree(): string {
  return `#!/usr/bin/env bun
// AUTO-GENERATED by @suluk/platform — manually launch the SAME isolated-worktree CI (scripts/ci-run.ts) on any ref (default
// HEAD), WITHOUT a push. Detaches + returns instantly, so several can run IN PARALLEL, each in its own worktree + log.
//   bun run ci:worktree                 # gates on HEAD
//   bun run ci:worktree <ref> --deploy  # gates + deploy (only meaningful on the default branch)
// Watch: git tag -l 'ci/<sha7>/*'   Log: .ci/<sha>.log
import { spawn, spawnSync } from "node:child_process";
import { mkdirSync, openSync } from "node:fs";
import { resolve } from "node:path";

const argv = process.argv.slice(2);
const deploy = argv.includes("--deploy");
const ref = argv.find((a) => !a.startsWith("--")) ?? "HEAD";
const root = resolve(import.meta.dir, "..");
const rev = spawnSync("git", ["rev-parse", ref], { cwd: root, encoding: "utf8" });
if (rev.status !== 0) { console.error(\`✗ ci:worktree — "\${ref}" is not a valid git ref.\\n\${rev.stderr ?? ""}\`); process.exit(1); }
const sha = rev.stdout.trim();
const short = sha.slice(0, 7);

mkdirSync(\`\${root}/.ci\`, { recursive: true });
const logFd = openSync(\`\${root}/.ci/\${sha}.log\`, "a");
// detached: a new session (POSIX setsid) + unref() → survives this command exiting; output to a file, not a pipe to us.
const child = spawn("bun", [\`\${root}/scripts/ci-run.ts\`, sha, deploy ? "1" : "0"], { cwd: root, detached: true, stdio: ["ignore", logFd, logFd], env: { ...process.env, SULUK_CI: "1" } });
child.unref();

console.log(\`⚡ Suluk CI launched in an isolated worktree for \${short} (deploy=\${deploy ? 1 : 0})\`);
console.log(\`   log:     .ci/\${sha}.log\`);
console.log(\`   verdict: git tag -l 'ci/\${short}/*'\`);
`;
}

/** `scripts/emit-contract.ts` — derive the v4 doc from the contract into openapi.v4.json (the input to the suluk gate). */
export function buildEmitContract(): string {
  return `#!/usr/bin/env bun
// AUTO-GENERATED by @suluk/platform — write the v4 "Suluk" contract (from apiDocument()) to openapi.v4.json (gitignored), the
// input the conformance gate (scripts/conformance.ts) audits. Run: \`bun run scripts/emit-contract.ts\` (the suluk:gate script does this first).
import { apiDocument } from "../src/contract";
await Bun.write("openapi.v4.json", JSON.stringify(apiDocument(), null, 2) + "\\n");
console.log("✓ wrote openapi.v4.json");
`;
}

/** `eslint.config.js` — flat config (ESLint 10). Correctness-first (Prettier owns formatting). The generated app carries
 *  FETCHED registry modules (own-the-code), so the type-aware "no any/as/!" bar is a WARN here (not a build-breaking error)
 *  — real bugs (unused vars, unreachable) still fail; run `bun run lint:fix` to auto-clean. Tighten to taste. */
export function buildEslintConfig(): string {
  return `// AUTO-GENERATED by @suluk/platform — flat config (ESLint 10). Prettier owns formatting; this catches real bugs. The app
// carries FETCHED registry modules you OWN, so the "no any/as/!" quality bar is a WARN (not fatal) — genuine errors still
// fail. Run \`bun run lint:fix\` to auto-clean, then tighten these to "error" as you make the code yours.
import js from "@eslint/js";
import tseslint from "typescript-eslint";
import globals from "globals";

export default tseslint.config(
  { ignores: ["node_modules/", "dist/", ".wrangler/", ".suluk/", ".ci/", "bun.lock", "openapi.v4.json", "**/*.min.js"] },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    files: ["**/*.ts"],
    languageOptions: { globals: { ...globals.node, Bun: "readonly" } },
    // The generated app carries FETCHED registry modules you OWN — hold their STYLE loosely (WARN: visible but non-blocking,
    // so a fresh app is lint-GREEN on its first push). Tighten these to "error" as you make the code yours. Genuine
    // correctness bugs (no-undef, no-dupe-keys, no-unreachable, no-const-assign, … from js/tseslint recommended) stay FATAL.
    rules: {
      "@typescript-eslint/no-explicit-any": "warn",
      "@typescript-eslint/no-non-null-assertion": "off",
      "@typescript-eslint/no-unused-vars": ["warn", { argsIgnorePattern: "^_", varsIgnorePattern: "^_", caughtErrors: "none" }],
      "@typescript-eslint/ban-ts-comment": "warn",
      "no-empty": "warn",
      "no-useless-escape": "warn",
    },
  },
);
`;
}

/** `.prettierrc.json` — formatting rules (Prettier owns style; ESLint owns correctness). */
export function buildPrettierrc(): string {
  return JSON.stringify({ printWidth: 160, tabWidth: 2, semi: true, singleQuote: false, trailingComma: "all" }, null, 2) + "\n";
}
