/**
 * The plan (C051) — PURE: a manifest → the shadcn-add list + the generated `src/index.ts` (the wired Hono entry) + the
 * generated `provision.config.ts` (importing + merging the fragments). No I/O; `generate` executes this. Testable to the
 * character.
 */
import type { PlatformManifest } from "./manifest";
import { CATALOG, orderServices } from "./catalog";

export interface PlatformPlan {
  services: string[];
  /** shadcn refs to add, in order (e.g. "MahmoodKhalil57/suluk/credits"). */
  adds: string[];
  /** the generated `src/index.ts` content. */
  entry: string;
  /** the generated `provision.config.ts` content. */
  provisionConfig: string;
}

export function planPlatform(manifest: PlatformManifest): PlatformPlan {
  const services = orderServices(manifest.services);
  const unknown = services.filter((s) => !CATALOG[s]);
  if (unknown.length) throw new Error(`platform: unknown service(s) [${unknown.join(", ")}] — not in the catalog`);
  return {
    services,
    adds: services.map((s) => `${manifest.registry}/${s}`),
    entry: buildEntry(services, manifest.opts),
    provisionConfig: buildProvisionConfig(services),
  };
}

function buildEntry(services: string[], opts?: Record<string, Record<string, unknown>>): string {
  const imports = ['import { createApp } from "./app";'];
  const middleware: string[] = [];
  const routes: string[] = [];
  // per-service static options → a JSON literal passed to the mount (e.g. auth's mcp OAuth config). Empty ⇒ no 2nd arg.
  const optOf = (s: string): string => {
    const o = opts?.[s];
    return o && Object.keys(o).length ? `, ${JSON.stringify(o)}` : "";
  };
  // TWO passes: ALL middleware mounts (app.use / handler) emit BEFORE any route mount, so a cross-cutting concern
  // (auth, rate-limit, i18n) applies to every route regardless of where it sits in the manifest.
  for (const s of services) {
    const m = CATALOG[s].mount;
    if (m.kind === "middleware") {
      imports.push(`import { ${m.symbol} } from "${m.from}";`);
      middleware.push(`${m.symbol}(app${optOf(s)});`);
    } else if (m.kind === "route") {
      imports.push(`import { ${m.symbol} } from "${m.from}";`);
      routes.push(`app.route("${m.path}", ${m.symbol}(${optOf(s).replace(/^, /, "")}));`);
    }
  }
  const body = ["const app = createApp();", ...middleware, ...routes];
  return `// AUTO-GENERATED by @suluk/platform from platform.config.ts — the wired Hono entry. Edit freely.\n${imports.join("\n")}\n\n${body.join("\n")}\n\nexport default app;\n`;
}

function buildProvisionConfig(services: string[]): string {
  const frags = services.map((s) => CATALOG[s].provision).filter((p): p is NonNullable<typeof p> => !!p);
  const imports = frags.map((f) => `import { ${f.symbol} } from "${f.from}";`);
  return [
    "// AUTO-GENERATED by @suluk/platform — the merged provision config. Run `suluk-provision apply`.",
    'import { defineProvision } from "@suluk/provision";',
    'import { mergeProvision } from "@suluk/platform";',
    ...imports,
    "",
    `export default defineProvision({ instances: mergeProvision([${frags.map((f) => f.symbol).join(", ")}]) });`,
    "",
  ].join("\n");
}
