/**
 * The RUNNABLE emitter (C038): a bound feature set → a self-contained `bun:test` suite that drives each scenario
 * through the consumer's GENERATED @suluk/sdk client (+ its reactive stores), against a LIVE deployment.
 *
 * Why the SDK client and not raw HTTP (the distinction from @suluk/testgen, which calls a raw `fetch(BASE+path)`
 * harness): the SDK client is the SAME one a Suluk frontend ships on, so a green scenario exercises the real frontend
 * DATA-PATH — typed dispatch, input validation, the auth interceptor, response decode, and the C037 store
 * invalidation/refetch. HONEST BOUNDARY (emitted as a literal header in the suite): it tests
 * client + contract + wire + the store data layer, NOT rendered UI / layout / visual — there is no DOM in a bun:test.
 *
 * The call site is lowered with @suluk/sdk's OWN `resolveOps` + `clientAccessor` — the single source of accessor
 * identity — so the emitted `client.<ns>.<member>(…)` can NEVER drift from the method `generateSdk` actually emits.
 * Journeys keeps `op.name@path` as the stable handle for IDENTITY; the SDK accessor (which `resolveOps` mutates) is
 * used ONLY here, at the late call-site lowering. Where an operation needs a request value the emitter writes a
 * "provide input" placeholder (a real NEEDS-DEV-GLUE), never an invented value (the never-launder-thin discipline).
 */
import type { OpenAPIv4Document } from "@suluk/core";
import { resolveOps, clientAccessor, type OpInfo } from "@suluk/sdk";
import type { Feature } from "./gherkin";
import type { Vocabulary } from "./vocabulary";
import { bindFeatures, type BindOptions } from "./bind";

export interface EmitOptions extends BindOptions {
  /** import specifier for the consumer's generated SDK (default: the consumer's local "./sdk"). */
  clientModule?: string;
  /** named export that creates a client (default: "createClient"). */
  clientFactory?: string;
  /** env var holding the live base URL (default: "SULUK_BASE_URL"). */
  baseUrlEnv?: string;
  /** env var holding a bearer token for authenticated scenarios (default: "SULUK_USER_TOKEN"). */
  tokenEnv?: string;
}

/** Emit a runnable bun:test suite (a string) from a parsed, bound feature set, lowered to the real SDK client. */
export function emitRunnableSuite(doc: OpenAPIv4Document, vocab: Vocabulary, features: Feature[], opts: EmitOptions = {}): string {
  const clientModule = opts.clientModule ?? "./sdk";
  const clientFactory = opts.clientFactory ?? "createClient";
  const baseUrlEnv = opts.baseUrlEnv ?? "SULUK_BASE_URL";
  const tokenEnv = opts.tokenEnv ?? "SULUK_USER_TOKEN";

  const report = bindFeatures(vocab, features, opts);
  // accessor identity comes from @suluk/sdk itself, keyed by the STABLE handle (name@uri — neither is mutated by resolveOps).
  const { ops } = resolveOps(doc);
  const opByHandle = new Map<string, OpInfo>(ops.map((op) => [`${op.name}@${op.uri}`, op]));

  const head = [
    "// GENERATED by @suluk/journeys — do not edit by hand; regenerate from the contract + .feature sidecars.",
    "// Coverage: this exercises the frontend DATA-PATH (client + contract + wire + store), NOT rendered UI / visual.",
    `import { test, expect } from "bun:test";`,
    `import { ${clientFactory} } from "${clientModule}";`,
    ``,
    `const client = ${clientFactory}({`,
    `  baseURL: process.env.${baseUrlEnv},`,
    `  token: () => process.env.${tokenEnv} ?? null, // bearer; cookie auth also works via credentials:"include"`,
    `});`,
    ``,
  ];

  const body: string[] = [];
  for (const sc of report.scenarios) {
    // emit a call for EACH bound When (a composed / multi-step journey drives several actions in order).
    const bound = sc.results.filter((r) => r.state === "BOUND" && r.step.kind === "when");
    if (!bound.length) continue;
    body.push(`test(${JSON.stringify(sc.scenario)}, async () => {`);
    let n = 0;
    let current: OpInfo | undefined;
    for (const r of sc.results) {
      if (r.state !== "BOUND") continue;
      if (r.step.kind === "when") {
        current = opByHandle.get(r.handle);
        if (!current) {
          body.push(`  // skipped ${r.handle} — not an SDK-surfaced operation (e.g. a webhook); bind via raw HTTP.`);
          continue;
        }
        const acc = clientAccessor(current); // e.g. "billing.checkout", "credits.get"
        body.push(`  // ${current.method.toUpperCase()} ${current.uri}${current.requires !== "anyone" ? `  (requires ${current.requires}: set ${tokenEnv})` : ""}`);
        body.push(`  const result${++n} = await client.${acc}(/* provide input */);`);
      } else if (r.step.kind === "then" && current) {
        if (/succeed/i.test(r.step.text) && n) body.push(`  expect(result${n}).toBeDefined();`);
        if (/refresh/i.test(r.step.text)) for (const key of current.store?.invalidates ?? []) body.push(`  // store: expect $${key} to have refreshed after this mutation`);
      }
    }
    body.push(`});`, ``);
  }

  if (!body.length) body.push("// No scenario bound a When-operation yet — author steps from the generated phrasebook.");
  return head.join("\n") + body.join("\n");
}
