#!/usr/bin/env bun
/**
 * AUTO-GENERATED by @suluk/platform — the .env lifecycle. Wired as `predev` (runs before `dev`) + `bun run check`.
 * The MINIMUM secret keys this app needs come from platform.config.ts (the selected modules). Non-secret config is in
 * the manifest `vars` → wrangler.toml [vars], not here.
 */
import { existsSync, readFileSync, writeFileSync, rmSync } from "node:fs";

const REQUIRED = ["BETTER_AUTH_SECRET","STRIPE_SECRET_KEY","STRIPE_WEBHOOK_SECRET"];
const ENV = ".env", TEMP = ".env.temp", EXAMPLE = ".env.example";

const parse = (p: string): Record<string, string> => {
  const out: Record<string, string> = {};
  for (const line of readFileSync(p, "utf8").split("\n")) {
    const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*)$/);
    if (m && m[2].trim()) out[m[1]] = m[2].trim();
  }
  return out;
};

const have = existsSync(ENV) ? parse(ENV) : {};
const missing = REQUIRED.filter((k) => !have[k] && !process.env[k]);

if (missing.length === 0) {
  if (existsSync(TEMP)) { rmSync(TEMP); console.log("✓ .env ready — removed .env.temp"); }
  else console.log("✓ .env ready (all required secrets present).");
  process.exit(0);
}

// not ready → drop a fill-me-in template so you can see exactly what's needed.
if (existsSync(EXAMPLE)) writeFileSync(TEMP, readFileSync(EXAMPLE, "utf8"));
console.error("✗ missing required secret(s): " + missing.join(", "));
console.error("  → wrote .env.temp — fill the values in and save it as .env (or inject the secrets another way).");
console.error("    .env.temp auto-deletes once .env has every required secret.");
process.exit(1);
