#!/usr/bin/env bun
/**
 * AUTO-GENERATED by @suluk/platform — the DEPLOY/PROVISION readiness preflight (run it manually: `bun run check`). It is
 * DELIBERATELY NOT wired to `bun dev`: local dev is mock-until-keyed and must run with ZERO secrets, so gating it here would
 * defeat the purpose. SETUP for going live: fill `.env.temp` (plaintext) then `bun run provision`. This verifies the END
 * STATE: a keypair exists, the required secrets are set + ENCRYPTED in the committed .env, and none is sitting in plaintext.
 * Non-secret config is in platform.config.ts `vars`.
 */
import { existsSync, readFileSync } from "node:fs";

const REQUIRED = ["CLOUDFLARE_ACCOUNT_ID","BETTER_AUTH_SECRET","STRIPE_SECRET_KEY","STRIPE_WEBHOOK_SECRET"];

const parse = (p: string): Record<string, string> => {
  const out: Record<string, string> = {};
  for (const line of readFileSync(p, "utf8").split("\n")) {
    const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*)$/);
    if (m && m[2].trim()) out[m[1]] = m[2].trim().replace(/^["']|["']$/g, "");
  }
  return out;
};
const fail = (msg: string) => { console.error("✗ " + msg); process.exit(1); };

// a plaintext bootstrap is waiting to be consumed → provision it (encrypts the keepers, deletes the master).
if (existsSync(".env.temp")) fail(".env.temp is present (plaintext) — run `bun run provision` to consume it (seals secrets into .env, deletes the master token).");

const have = existsSync(".env") ? parse(".env") : {};
const isEncrypted = (v: string) => v.startsWith("encrypted:");
if (!have.SULUK_PUBLIC_KEY) fail("no keypair yet — fill .env.temp with your creds/secrets and run `bun run provision` (creates the keypair, provisions, seals secrets).");

const missing = REQUIRED.filter((k) => !have[k] && !process.env[k]);
if (missing.length) fail("missing required secret(s) in .env: " + missing.join(", ") + "\n  → add them to .env.temp + `bun run provision`, or `bunx suluk-env set KEY=value`");

const plaintext = Object.keys(have).filter((k) => k !== "SULUK_PUBLIC_KEY" && have[k] && !isEncrypted(have[k]));
if (plaintext.length) fail("PLAINTEXT secret(s) in .env (never commit these): " + plaintext.join(", ") + "\n  → encrypt: bunx suluk-env encrypt");

console.log("✓ .env ready — keypair present, required secrets set + encrypted.");
process.exit(0);
