#!/usr/bin/env bun
/**
 * AUTO-GENERATED by @suluk/platform — the ENCRYPTED-env preflight (wired as `predev` + `bun run check`). Secrets live in the
 * committed .env, ENCRYPTED with @suluk/env. This checks: a keypair exists, the REQUIRED secrets are set, and none is sitting
 * in plaintext (which must never be committed). Non-secret config is in platform.config.ts `vars` → wrangler.toml [vars].
 */
import { existsSync, readFileSync } from "node:fs";

const REQUIRED = ["BETTER_AUTH_SECRET","STRIPE_SECRET_KEY","STRIPE_WEBHOOK_SECRET"];
const ENV = ".env";

const parse = (p: string): Record<string, string> => {
  const out: Record<string, string> = {};
  for (const line of readFileSync(p, "utf8").split("\n")) {
    const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*)$/);
    if (m && m[2].trim()) out[m[1]] = m[2].trim().replace(/^["']|["']$/g, "");
  }
  return out;
};

const have = existsSync(ENV) ? parse(ENV) : {};
const isEncrypted = (v: string) => v.startsWith("encrypted:");
const fail = (msg: string) => { console.error("✗ " + msg); process.exit(1); };

if (!have.SULUK_PUBLIC_KEY) fail("no @suluk/env keypair — run `bunx suluk-env keygen` (creates SULUK_PUBLIC_KEY in .env + .env.keys).");

const missing = REQUIRED.filter((k) => !have[k] && !process.env[k]);
if (missing.length) fail("missing required secret(s): " + missing.join(", ") + "\n  → set each: bunx suluk-env set KEY=value");

const plaintext = Object.keys(have).filter((k) => k !== "SULUK_PUBLIC_KEY" && have[k] && !isEncrypted(have[k]));
if (plaintext.length) fail("PLAINTEXT secret(s) in .env (never commit these): " + plaintext.join(", ") + "\n  → encrypt: bunx suluk-env encrypt");

console.log("✓ .env ready — keypair present, required secrets set + encrypted.");
process.exit(0);
