// AUTO-GENERATED by @suluk/platform — flat config (ESLint 10). Prettier owns formatting; this catches real bugs. The app
// carries FETCHED registry modules you OWN, so the "no any/as/!" quality bar is a WARN (not fatal) — genuine errors still
// fail. Run `bun run lint:fix` to auto-clean, then tighten these to "error" as you make the code yours.
import js from "@eslint/js";
import tseslint from "typescript-eslint";
import globals from "globals";

export default tseslint.config(
  { ignores: ["node_modules/", "dist/", ".wrangler/", ".suluk/", ".ci/", "bun.lock", "openapi.v4.json", "**/*.min.js"] },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    files: ["**/*.ts"],
    languageOptions: { globals: { ...globals.node, Bun: "readonly" } },
    // The generated app carries FETCHED registry modules you OWN — hold their STYLE loosely (WARN: visible but non-blocking,
    // so a fresh app is lint-GREEN on its first push). Tighten these to "error" as you make the code yours. Genuine
    // correctness bugs (no-undef, no-dupe-keys, no-unreachable, no-const-assign, … from js/tseslint recommended) stay FATAL.
    rules: {
      "@typescript-eslint/no-explicit-any": "warn",
      "@typescript-eslint/no-non-null-assertion": "off",
      "@typescript-eslint/no-unused-vars": ["warn", { argsIgnorePattern: "^_", varsIgnorePattern: "^_", caughtErrors: "none" }],
      "@typescript-eslint/ban-ts-comment": "warn",
      "no-empty": "warn",
      "no-useless-escape": "warn",
    },
  },
);
