#!/usr/bin/env bun
// AUTO-GENERATED by @suluk/platform. Register this project's @suluk/env private key into ~/.suluk/settings.json (keyed by the
// repo path) — the central, out-of-git store @suluk/env reads by default. Run once after `bunx suluk-env keygen`; idempotent.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { homedir } from "node:os";
import { join, dirname } from "node:path";
import { readPrivateKey } from "@suluk/env/node";

const repo = process.cwd();
const name = repo.split("/").filter(Boolean).pop() ?? "project";
const priv = readPrivateKey(); // SULUK_PRIVATE_KEY env > ~/.suluk/settings.json > .env.keys (legacy)
if (!priv) { console.error("✗ no private key — run `bunx suluk-env keygen` first"); process.exit(1); }

const settingsPath = process.env.SULUK_SETTINGS_PATH || join(homedir(), ".suluk", "settings.json");
type Proj = { name?: string; path?: string; env?: Array<{ key: string; value: string }> };
let data: { projects?: Proj[] } = {};
try { data = JSON.parse(readFileSync(settingsPath, "utf8")); } catch { /* fresh */ }
const projects: Proj[] = Array.isArray(data.projects) ? data.projects : [];
let entry = projects.find((p) => p.path === repo);
if (!entry) { entry = { name, path: repo, env: [] }; projects.push(entry); }
entry.name = name; entry.path = repo; entry.env = Array.isArray(entry.env) ? entry.env : [];
const existing = entry.env.find((e) => e.key === "SULUK_PRIVATE_KEY");
if (existing) existing.value = priv; else entry.env.push({ key: "SULUK_PRIVATE_KEY", value: priv });
data.projects = projects;
mkdirSync(dirname(settingsPath), { recursive: true });
writeFileSync(settingsPath, JSON.stringify(data, null, 2) + "\n");
console.log(`✓ linked ${name} → ${settingsPath}. You can now \`rm .env.keys\` — the key lives in the central store.`);
