#!/usr/bin/env bun
// AUTO-GENERATED by @suluk/platform. Mint scoped least-privilege CF tokens FROM the master (CLOUDFLARE_API_TOKEN), each
// stored ENCRYPTED in .env via `suluk-env set`. Routine deploy/migrate then use these, not the master. Idempotent.
import { setVar, loadEnvFile, rawEnvRecord } from "@suluk/env/node";

await loadEnvFile({ override: true });
const token = process.env.CLOUDFLARE_API_TOKEN, acct = process.env.CLOUDFLARE_ACCOUNT_ID;
if (!token || !acct) { console.error("✗ CLOUDFLARE_API_TOKEN / CLOUDFLARE_ACCOUNT_ID required (put them in .env.temp, run `bun run provision`)"); process.exit(1); }

const SCOPED = [
  { name: "CLOUDFLARE_D1_TOKEN", groups: ["D1 Write"] },
  { name: "CLOUDFLARE_WORKERS_TOKEN", groups: ["Workers Scripts Write"] },
  { name: "CLOUDFLARE_KV_TOKEN", groups: ["Workers KV Storage Write"] },
];
// resolve the CF permission-group ids once (POST /accounts/{id}/tokens needs ids, not names).
const pgRes = await fetch("https://api.cloudflare.com/client/v4/user/tokens/permission_groups", { headers: { Authorization: `Bearer ${token}` } });
const pg = (await pgRes.json()) as { result?: Array<{ id: string; name: string }> };
const idOf = (name: string) => pg.result?.find((g) => g.name === name)?.id;

const have = rawEnvRecord();
for (const s of SCOPED) {
  if (have[s.name]) { console.log(`– skip ${s.name} (already set)`); continue; }
  const permission_groups = s.groups.map((n) => ({ id: idOf(n) })).filter((g) => g.id);
  const res = await fetch(`https://api.cloudflare.com/client/v4/accounts/${acct}/tokens`, {
    method: "POST",
    headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" },
    body: JSON.stringify({ name: `${s.name.toLowerCase()}`, policies: [{ effect: "allow", resources: { [`com.cloudflare.api.account.${acct}`]: "*" }, permission_groups }] }),
  });
  const out = (await res.json()) as { success?: boolean; result?: { value?: string }; errors?: unknown };
  if (!out.success || !out.result?.value) { console.error(`✗ mint ${s.name}: ${JSON.stringify(out.errors)}`); process.exit(1); }
  await setVar(s.name, out.result.value); // encrypted into .env; never printed
  console.log(`✓ minted ${s.name}`);
}
console.log("✓ scoped tokens ready (encrypted in .env).");
