#!/usr/bin/env bun
// AUTO-GENERATED by @suluk/platform — stand up the infra + SEAL the secrets (@suluk/env encrypted-commit model). Run once
// after filling .env.temp (or with an existing encrypted .env). Idempotent. IMPORTS the tools (no spawning Suluk CLIs); the
// only subprocess is `git add` (staging the encrypted .env). No wrangler, no ambient credentials.
import { existsSync, rmSync, readFileSync, writeFileSync } from "node:fs";
import { randomBytes } from "node:crypto";
import { loadEnvFile, setVar, ensureKeypair, encryptEnvFile } from "@suluk/env/node";
import { runCli } from "@suluk/provision";
import { linkKey } from "./link-key";
import { mintTokens } from "./mint-tokens";

const EPHEMERAL = ["CLOUDFLARE_API_TOKEN"]; // the CF master token(s): used to provision + mint, then DELETED (never committed)
const GENERATED = ["BETTER_AUTH_SECRET"]; // secrets the app creates itself (e.g. BETTER_AUTH_SECRET) — never operator-supplied

// 1. keypair → the central ~/.suluk/settings.json (the private key never stays in the repo). ensureKeypair is idempotent.
const kp = ensureKeypair(); // creates the @suluk/env keypair (private → .env.keys) if absent, else returns the existing one
await setVar("SULUK_PUBLIC_KEY", kp.publicKey, { plain: true }); // the public key lives (plaintext) in .env, as `suluk-env keygen` does
linkKey(); // register the private key in ~/.suluk/settings.json (imported from ./link-key)
rmSync(".env.keys", { force: true });

// 2. source the raw creds: .env.temp (plaintext, first run) → stage into .env, then it's consumed; else the encrypted .env.
if (existsSync(".env.temp")) {
  for (const l of readFileSync(".env.temp", "utf8").split("\n")) {
    const m = l.match(/^\s*([A-Z0-9_]+)\s*=\s*(.+)$/);
    if (m && m[2].trim()) await setVar(m[1], m[2].trim().replace(/^["']|["']$/g, ""), { plain: true }); // stage plaintext (encrypted at step 5)
  }
}
await loadEnvFile({ override: true }); // decrypt everything into process.env
if (!process.env.CLOUDFLARE_API_TOKEN || !process.env.CLOUDFLARE_ACCOUNT_ID) { console.error("✗ CLOUDFLARE_API_TOKEN / CLOUDFLARE_ACCOUNT_ID missing — put them in .env.temp"); process.exit(1); }

// 2b. auto-generate any app-created secret (e.g. BETTER_AUTH_SECRET ← 32 random bytes) not already set — the operator never
//     supplies these in .env.temp. Staged plaintext here, encrypted at step 5.
for (const name of GENERATED) {
  if (!process.env[name]) { await setVar(name, randomBytes(32).toString("base64"), { plain: true }); console.log(`✓ generated ${name}`); }
}

// 3. provision the infra (D1/KV — the C047 provision.config) via @suluk/provision (imported), 4. mint the scoped tokens.
// IMPORT THE CONFIG NOW (dynamic) — AFTER loadEnvFile — so provision.config's Cloudflare brokers pick up the decrypted creds.
const { default: provisionApp } = await import("../provision.config");
const { output, exitCode } = await runCli(provisionApp, ["apply"]);
if (output) console.log(output);
if (exitCode !== 0) process.exit(exitCode);
await mintTokens(); // imported from ./mint-tokens (fetch over the CF API — no wrangler)

// 5. ENCRYPT every keeper value in .env in place (runtime secrets + account id + minted tokens).
await encryptEnvFile();

// 6. DELETE the ephemeral master token from .env (never committed) — routine ops use the minted scoped tokens.
if (EPHEMERAL.length) {
  const kept = readFileSync(".env", "utf8").split("\n").filter((l) => { const m = l.match(/^\s*([A-Z0-9_]+)\s*=/); return !(m && EPHEMERAL.includes(m[1])); });
  writeFileSync(".env", kept.join("\n"));
}
// 7. consume the plaintext bootstrap + stage the encrypted .env (git is the one remaining subprocess — not a credential CLI).
rmSync(".env.temp", { force: true });
{ const p = Bun.spawn(["git", "add", "-f", ".env"], { stdout: "inherit", stderr: "inherit" }); if ((await p.exited) !== 0) { console.error("✗ git add -f .env"); process.exit(1); } }
console.log("✓ provisioned + sealed: infra up, secrets encrypted in .env; the CF master token was removed from .env.");
console.log("");
console.log("⚠ REVOKE the master CF token in the dashboard now (https://dash.cloudflare.com/profile/api-tokens) — it minted the");
console.log("  scoped least-privilege tokens and is no longer needed. Routine deploy/migrate use the minted tokens. To create new");
console.log("  services / mint new tokens / teardown later, generate a FRESH master token, put it in .env.temp, re-run `bun run provision`.");
console.log("");
console.log("Next: `bun run deploy` (ships the Worker + pushes SULUK_PRIVATE_KEY so it decrypts the committed .env at runtime).");
