// AUTO-GENERATED by @suluk/platform — the merged provision config. Run `suluk-provision apply`.
import { defineProvision } from "@suluk/provision";
import { mergeProvision } from "@suluk/platform";
import { authProvision } from "./src/provision/auth";
import { mcpProvision } from "./src/provision/mcp";
import { creditsProvision } from "./src/provision/credits";
import { keysProvision } from "./src/provision/keys";
import { billingProvision } from "./src/provision/billing";
import { costProvision } from "./src/provision/cost";
import { erasureProvision } from "./src/provision/erasure";
import { webhooksProvision } from "./src/provision/webhooks";
import { logsProvision } from "./src/provision/logs";

export default defineProvision({ instances: mergeProvision([authProvision, mcpProvision, creditsProvision, keysProvision, billingProvision, costProvision, erasureProvision, webhooksProvision, logsProvision]) });
