#!/usr/bin/env bun
// AUTO-GENERATED by @suluk/platform — stand up the infra + SEAL the secrets (@suluk/env encrypted-commit model). Run once
// after filling .env.temp (or with an existing encrypted .env). Idempotent.
import { existsSync, rmSync, readFileSync, writeFileSync } from "node:fs";
import { loadEnvFile, setVar } from "@suluk/env/node";

const EPHEMERAL = ["CLOUDFLARE_API_TOKEN"]; // the CF master token(s): used to provision + mint, then DELETED (never committed)
const sh = async (cmd: string, args: string[]) => { const p = Bun.spawn([cmd, ...args], { stdout: "inherit", stderr: "inherit" }); if ((await p.exited) !== 0) { console.error(`✗ ${cmd} ${args.join(" ")}`); process.exit(1); } };

// 1. keypair → the central ~/.suluk/settings.json (the private key never stays in the repo).
await Bun.spawn(["bunx", "suluk-env", "keygen"]).exited; // idempotent (nonzero if a key already exists)
await sh("bun", ["run", "scripts/link-key.ts"]);
rmSync(".env.keys", { force: true });

// 2. source the raw creds: .env.temp (plaintext, first run) → stage into .env, then it's consumed; else the encrypted .env.
if (existsSync(".env.temp")) {
  for (const l of readFileSync(".env.temp", "utf8").split("\n")) {
    const m = l.match(/^\s*([A-Z0-9_]+)\s*=\s*(.+)$/);
    if (m && m[2].trim()) await setVar(m[1], m[2].trim().replace(/^["']|["']$/g, ""), { plain: true }); // stage plaintext (encrypted at step 5)
  }
}
await loadEnvFile({ override: true }); // decrypt everything into process.env
if (!process.env.CLOUDFLARE_API_TOKEN || !process.env.CLOUDFLARE_ACCOUNT_ID) { console.error("✗ CLOUDFLARE_API_TOKEN / CLOUDFLARE_ACCOUNT_ID missing — put them in .env.temp"); process.exit(1); }

// 3. provision the infra (D1/KV — the C047 provision.config), 4. mint the scoped least-privilege tokens from the master.
await sh("bunx", ["suluk-provision", "apply"]);
await sh("bun", ["run", "scripts/mint-tokens.ts"]);

// 5. ENCRYPT every keeper value in .env in place (runtime secrets + account id + minted tokens).
await sh("bunx", ["suluk-env", "encrypt"]);

// 6. DELETE the ephemeral master token from .env (never committed) — routine ops use the minted scoped tokens.
if (EPHEMERAL.length) {
  const kept = readFileSync(".env", "utf8").split("\n").filter((l) => { const m = l.match(/^\s*([A-Z0-9_]+)\s*=/); return !(m && EPHEMERAL.includes(m[1])); });
  writeFileSync(".env", kept.join("\n"));
}
// 7. consume the plaintext bootstrap + stage the encrypted .env.
rmSync(".env.temp", { force: true });
await sh("git", ["add", "-f", ".env"]);
console.log("✓ provisioned + sealed: infra up, secrets encrypted in .env; the CF master token was removed from .env.");
console.log("");
console.log("⚠ REVOKE the master CF token in the dashboard now (https://dash.cloudflare.com/profile/api-tokens) — it minted the");
console.log("  scoped least-privilege tokens and is no longer needed. Routine deploy/migrate use the minted tokens. To create new");
console.log("  services / mint new tokens / teardown later, generate a FRESH master token, put it in .env.temp, re-run `bun run provision`.");
console.log("");
console.log("Next: `bun run deploy` (ships the Worker + pushes SULUK_PRIVATE_KEY so it decrypts the committed .env at runtime).");
