// AUTO-GENERATED by @suluk/platform — the ONE ordered CI stage list, shared by scripts/ci-run.ts (async/worktree/deploy)
// and scripts/ci-local.ts (in-place `bun run ci:local`) so they can NEVER drift. Ordered cheap→expensive to fail fast.
// Every stage is IDEMPOTENT: it reads/checks only (format:check doesn't write; bundle:check builds to the gitignored .ci/;
// test/typecheck/lint mutate nothing) — run it twice → identical result. Deploy is NOT a stage (ci-run runs it after all pass).
export interface Stage {
  label: string;
  cmd: string[];
}

export const STAGES: readonly Stage[] = [
  { label: "format", cmd: ["bun", "run", "format:check"] },     // prettier --check — no writes
  { label: "lint", cmd: ["bun", "run", "lint"] },               // eslint
  { label: "typecheck", cmd: ["bun", "run", "typecheck"] },     // tsc --noEmit
  { label: "suluk-gate", cmd: ["bun", "run", "suluk:gate"] },   // the unified conformance gate (@suluk/cockpit + @suluk/harden)
  { label: "bundle", cmd: ["bun", "run", "bundle:check"] },     // the Worker bundles (same Bun.build the deploy runs)
  { label: "test", cmd: ["bun", "test"] },
];
