#!/usr/bin/env bun
// AUTO-GENERATED by @suluk/platform — write the v4 "Suluk" contract (from apiDocument()) to openapi.v4.json (gitignored), the
// input the conformance gate (scripts/conformance.ts) audits. Run: `bun run scripts/emit-contract.ts` (the suluk:gate script does this first).
import { apiDocument } from "../src/contract";
await Bun.write("openapi.v4.json", JSON.stringify(apiDocument(), null, 2) + "\n");
console.log("✓ wrote openapi.v4.json");
