#!/usr/bin/env bun
// AUTO-GENERATED by @suluk/platform — run the full CI pipeline (scripts/ci-stages.ts) IN-PLACE: the local equivalent of the
// async pre-push CI, minus the worktree / tags / deploy. Same ordered, fail-fast, idempotent stages. `bun run ci:local`
import { spawnSync } from "node:child_process";
import { STAGES } from "./ci-stages";

console.log(`──── Suluk CI (local · ${STAGES.length} stages) ────`);
for (const s of STAGES) {
  console.log(`\n── ${s.label} ──`);
  const r = spawnSync(s.cmd[0] ?? "", s.cmd.slice(1), { stdio: "inherit" });
  if (r.status !== 0) { console.error(`\n✗ CI failed at stage: ${s.label}`); process.exit(r.status ?? 1); }
}
console.log("\n✅ CI passed — all stages green.");
