#!/usr/bin/env bun
// AUTO-GENERATED by @suluk/platform — write the AsyncAPI 3.0 + CloudEvents projection of the v4 contract
// (emitAsyncApi(apiDocument())) to asyncapi.json (gitignored) — the app's EVENT surface: background jobs, inbound
// webhooks, and the reactive-store invalidations a mutation emits. The async companion to scripts/emit-contract.ts.
import { emitAsyncApi } from "@suluk/hono";
import { apiDocument } from "../src/contract";
await Bun.write("asyncapi.json", JSON.stringify(emitAsyncApi(apiDocument()), null, 2) + "\n");
console.log("✓ wrote asyncapi.json");
