#!/usr/bin/env bun
/**
 * AUTO-GENERATED by @suluk/platform — the DETACHED CI runner launched by .githooks/pre-push (the hook returns instantly).
 * Runs the pipeline in an ISOLATED git worktree at the pushed commit, so it never touches your working tree — safe to run
 * async while you keep editing. Flow: worktree add → STAGES (fail-fast) → deploy (if the default branch) → tags → cleanup.
 * Progress is recorded as LOCAL git tags: ci/<sha>/started · ok-<stage> · failed-<stage> · deployed · passed|failed.
 * Logs: .ci/<sha>.log.  Inspect: `git tag -l 'ci/<sha7>/*'`.
 */
import { spawnSync } from "node:child_process";
import { mkdirSync, symlinkSync, rmSync } from "node:fs";

const [sha = "", deployFlag = "0"] = process.argv.slice(2);
const deploy = deployFlag === "1";
const short = sha.slice(0, 7);
const run = (cmd: string, args: string[], opts: Parameters<typeof spawnSync>[2] = {}) => spawnSync(cmd, args, { encoding: "utf8", ...opts });
const repo = run("git", ["rev-parse", "--show-toplevel"]).stdout.trim();
const tag = (name: string) => run("git", ["tag", "-f", `ci/${short}/${name}`, sha], { cwd: repo });

const wt = `${process.env.TMPDIR ?? "/tmp"}/suluk-ci-${short}-${Date.now()}`;
mkdirSync(`${repo}/.ci`, { recursive: true });
console.log(`──── Suluk CI ${short} (deploy=${deploy}) ────`);
tag("started");

const cleanup = () => { run("git", ["worktree", "remove", "--force", wt], { cwd: repo }); run("git", ["worktree", "prune"], { cwd: repo }); };
process.on("exit", cleanup);

if (run("git", ["worktree", "add", "--detach", wt, sha], { cwd: repo, stdio: "inherit" }).status !== 0) {
  tag("failed-worktree"); tag("failed"); process.exit(1);
}
// Reuse the dev tree's installed deps (no reinstall per push); @suluk/env reads the real repo's key via SULUK_PROJECT_DIR.
try { rmSync(`${wt}/node_modules`, { recursive: true, force: true }); symlinkSync(`${repo}/node_modules`, `${wt}/node_modules`); } catch {}
const childEnv = { ...process.env, SULUK_PROJECT_DIR: repo, SULUK_CI: "1" };

// The pipeline lives in scripts/ci-stages.ts (shared with `bun run ci:local`) so the two can't drift.
const { STAGES } = await import(`${wt}/scripts/ci-stages.ts`);
let ok = true;
for (const { label, cmd } of STAGES as { label: string; cmd: string[] }[]) {
  console.log(`\n── ${label} ──`);
  const r = run(cmd[0] ?? "", cmd.slice(1), { cwd: wt, stdio: "inherit", env: childEnv });
  if (r.status !== 0) { tag(`failed-${label}`); ok = false; break; }
  tag(`ok-${label}`);
}

if (ok && deploy) {
  console.log("\n── deploy ──");
  const r = run("bun", ["run", "deploy"], { cwd: wt, stdio: "inherit", env: childEnv });
  if (r.status === 0) tag("deployed"); else { tag("deploy-failed"); ok = false; }
}

tag(ok ? "passed" : "failed");
console.log(ok ? "\n✅ CI passed" : "\n❌ CI failed");
process.exit(ok ? 0 : 1);
