#!/usr/bin/env bun
/**
 * AUTO-GENERATED by @suluk/platform — API-driven Cloudflare deploy (NO wrangler, NO ambient auth). Bundles src/index.ts,
 * then @suluk/deploy (over @suluk/cloudflare) provisions D1/KV, deploys the Worker with its bindings/vars, and pushes
 * secrets — all over the Cloudflare REST API. Credentials come from the @suluk/env-DECRYPTED .env (CLOUDFLARE_API_TOKEN +
 * optional CLOUDFLARE_ACCOUNT_ID). Run: `bun run deploy` (after `bun run provision`).
 */
import { deployCloudflare, type CloudflareDeploySpec } from "@suluk/deploy";
import { loadEnvFile, readPrivateKey } from "@suluk/env/node";

const NAME = "autotoolfactory";
const VARS: Record<string, string> = {"TRUSTED_ORIGINS":"https://autotoolfactory.example","BETTER_AUTH_URL":"https://autotoolfactory.example","EMAIL_FROM":"noreply@autotoolfactory.example","BRAND_NAME":"autotoolfactory","BASE_URL":"https://autotoolfactory.example","ENVIRONMENT":"production"};
const KV_BINDINGS = ["RATE_CREDIT_KV","RATE_LIMIT_KV"];
const SECRET_NAMES = ["CLOUDFLARE_API_TOKEN","CLOUDFLARE_ACCOUNT_ID","CLOUDFLARE_D1_TOKEN","CLOUDFLARE_WORKERS_TOKEN","CLOUDFLARE_KV_TOKEN","BETTER_AUTH_SECRET","GOOGLE_CLIENT_ID","GOOGLE_CLIENT_SECRET","STRIPE_SECRET_KEY","RESEND_API_KEY","STRIPE_WEBHOOK_SECRET","SUPERADMIN_EMAILS"]; // pushed if set (encrypted) in .env — SULUK_PRIVATE_KEY is always pushed

// 1) decrypt the committed .env → the resolved secrets/config. CF credentials come from HERE — never wrangler / the ambient system.
const cfg = await loadEnvFile();
const apiToken = cfg.CLOUDFLARE_D1_TOKEN ?? cfg.CLOUDFLARE_API_TOKEN; // the minted scoped token if present, else the master
if (!apiToken) { console.error("✗ no CLOUDFLARE_API_TOKEN in the decrypted .env — run `bun run provision` (or set it) first."); process.exit(1); }

// 2) the runtime SECRETS the Worker needs: SULUK_PRIVATE_KEY (decrypts the committed .env at runtime) + each set app secret.
const priv = readPrivateKey();
if (!priv) { console.error("✗ no private key (~/.suluk/settings.json / SULUK_PRIVATE_KEY) — run `bun run link-key`."); process.exit(1); }
const secrets: Record<string, string> = { SULUK_PRIVATE_KEY: priv };
for (const k of SECRET_NAMES) if (cfg[k] !== undefined && cfg[k] !== "") secrets[k] = cfg[k];

// 3) bundle src/index.ts → the Worker ES module (the Worker runtime provides nodejs_compat).
const built = await Bun.build({ entrypoints: ["src/index.ts"], format: "esm", minify: true });
if (!built.success) { for (const l of built.logs) console.error(l); process.exit(1); }
const workerModule = await built.outputs[0].text();

// 4) provision + deploy over the API. D1 (by name) + KV (by title) are IDEMPOTENT — reused across deploys.
const kv = KV_BINDINGS.map((binding) => ({ binding, title: `${NAME}-${binding.toLowerCase().replace(/_/g, "-")}` }));
const spec: CloudflareDeploySpec = {
  scriptName: NAME,
  module: workerModule,
  d1: { binding: "DB", databaseName: NAME },
  ...(kv.length ? { kv } : {}),
  vars: VARS,
  secrets,
};

console.log(`Deploying "${NAME}" to Cloudflare over the API (no wrangler)…`);
const res = await deployCloudflare({ apiToken, accountId: cfg.CLOUDFLARE_ACCOUNT_ID }, spec, (m) => console.log("  " + m));
console.log(`✓ deployed ${res.scriptName}${res.d1 ? ` · D1 ${res.d1.id}` : ""}${res.kv.length ? ` · KV ${res.kv.map((k) => k.binding).join(",")}` : ""} · ${res.secretsSet.length} secret(s)`);
