#!/usr/bin/env bun
// AUTO-GENERATED by @suluk/platform — manually launch the SAME isolated-worktree CI (scripts/ci-run.ts) on any ref (default
// HEAD), WITHOUT a push. Detaches + returns instantly, so several can run IN PARALLEL, each in its own worktree + log.
//   bun run ci:worktree                 # gates on HEAD
//   bun run ci:worktree <ref> --deploy  # gates + deploy (only meaningful on the default branch)
// Watch: git tag -l 'ci/<sha7>/*'   Log: .ci/<sha>.log
import { spawn, spawnSync } from "node:child_process";
import { mkdirSync, openSync } from "node:fs";
import { resolve } from "node:path";

const argv = process.argv.slice(2);
const deploy = argv.includes("--deploy");
const ref = argv.find((a) => !a.startsWith("--")) ?? "HEAD";
const root = resolve(import.meta.dir, "..");
const rev = spawnSync("git", ["rev-parse", ref], { cwd: root, encoding: "utf8" });
if (rev.status !== 0) { console.error(`✗ ci:worktree — "${ref}" is not a valid git ref.\n${rev.stderr ?? ""}`); process.exit(1); }
const sha = rev.stdout.trim();
const short = sha.slice(0, 7);

mkdirSync(`${root}/.ci`, { recursive: true });
const logFd = openSync(`${root}/.ci/${sha}.log`, "a");
// detached: a new session (POSIX setsid) + unref() → survives this command exiting; output to a file, not a pipe to us.
const child = spawn("bun", [`${root}/scripts/ci-run.ts`, sha, deploy ? "1" : "0"], { cwd: root, detached: true, stdio: ["ignore", logFd, logFd], env: { ...process.env, SULUK_CI: "1" } });
child.unref();

console.log(`⚡ Suluk CI launched in an isolated worktree for ${short} (deploy=${deploy ? 1 : 0})`);
console.log(`   log:     .ci/${sha}.log`);
console.log(`   verdict: git tag -l 'ci/${short}/*'`);
