// AUTO-GENERATED by @suluk/platform — the @suluk/env declare-once for this app's SECRETS. Values live ENCRYPTED in the
// committed .env (ML-KEM-768). Non-secret config is in platform.config.ts `vars` → wrangler.toml [vars].
import { defineEnv } from "@suluk/env";

export const env = defineEnv({
  BETTER_AUTH_SECRET: { secret: true, required: true, surfaces: ["cloudflare"], description: "session-signing key — `openssl rand -base64 32`" },
  GOOGLE_CLIENT_ID: { secret: true, surfaces: ["cloudflare"], description: "optional — enables Google sign-in" },
  GOOGLE_CLIENT_SECRET: { secret: true, surfaces: ["cloudflare"], description: "optional — pairs with GOOGLE_CLIENT_ID" },
  STRIPE_SECRET_KEY: { secret: true, required: true, surfaces: ["cloudflare"], description: "your Stripe secret key" },
  RESEND_API_KEY: { secret: true, surfaces: ["cloudflare"], description: "omit → the console provider (dev)" },
  STRIPE_WEBHOOK_SECRET: { secret: true, required: true, surfaces: ["cloudflare"], description: "verifies inbound Stripe events (POST /api/webhooks/stripe)" },
});
