// AUTO-GENERATED by @suluk/platform — the composed contract surface (one fragment per installed module).
import type { DocumentedRoute } from "@suluk/hono";
import { mcpOps } from "./contract/mcp";
import { creditsOps } from "./contract/credits";
import { keysOps } from "./contract/keys";
import { billingOps } from "./contract/billing";
import { costOps } from "./contract/cost";
import { erasureOps } from "./contract/erasure";
import { emailOps } from "./contract/email";
import { webhooksOps } from "./contract/webhooks";
import { logsOps } from "./contract/logs";
import { referenceOps } from "./contract/reference";
import { adminOps } from "./contract/admin";

export const ALL_OPS: readonly DocumentedRoute[] = [...mcpOps, ...creditsOps, ...keysOps, ...billingOps, ...costOps, ...erasureOps, ...emailOps, ...webhooksOps, ...logsOps, ...referenceOps, ...adminOps];
