// AUTO-GENERATED by @suluk/platform — the composed contract surface (one fragment per installed module).
import type { DocumentedRoute } from "@suluk/hono";
import { mcpOps } from "./routes/mcp";
import { creditsOps } from "./routes/credits";
import { keysOps } from "./routes/keys";
import { billingOps } from "./routes/billing";
import { costOps } from "./routes/cost";
import { erasureOps } from "./routes/erasure";
import { emailOps } from "./routes/email";
import { webhooksOps } from "./routes/webhooks";
import { logsOps } from "./routes/logs";
import { referenceOps } from "./routes/reference";
import { adminOps } from "./routes/admin";

export const ALL_OPS: readonly DocumentedRoute[] = [...mcpOps, ...creditsOps, ...keysOps, ...billingOps, ...costOps, ...erasureOps, ...emailOps, ...webhooksOps, ...logsOps, ...referenceOps, ...adminOps];
