#!/usr/bin/env bun
// AUTO-GENERATED by @suluk/platform. Push the committed, @suluk/env-encrypted secrets to the Worker as `wrangler secret`s.
// Run at deploy: `bun run sync-secrets`. Needs the private key (.env.keys / ~/.suluk / SULUK_PRIVATE_KEY) + a CF-authed wrangler.
import { loadEnvFile } from "@suluk/env/node";
import { env } from "../src/env";

const values = await loadEnvFile(); // decrypt every value in .env into a { KEY: value } record
const names = env.forSurface("cloudflare").filter((k) => values[k] !== undefined && values[k] !== "");
if (!names.length) {
  console.log("no cloudflare-surfaced secrets are set in .env yet — run `bunx suluk-env set KEY=value` first.");
  process.exit(0);
}
for (const name of names) {
  const proc = Bun.spawn(["wrangler", "secret", "put", name], { stdin: "pipe", stdout: "inherit", stderr: "inherit" });
  proc.stdin.write(values[name]);
  await proc.stdin.end();
  if ((await proc.exited) !== 0) { console.error(`✗ failed to put ${name}`); process.exit(1); }
  console.log(`✓ ${name}`);
}
console.log(`✓ synced ${names.length} secret(s) to the Worker.`);
