#!/usr/bin/env bun
// AUTO-GENERATED by @suluk/platform. Re-push SULUK_PRIVATE_KEY (so src/index.ts's loadEnv decrypts the committed .env at
// runtime) + each cloudflare-surfaced secret to the deployed Worker over the Cloudflare REST API — credentials from the
// @suluk/env-decrypted .env, NO wrangler. Run: `bun run sync-secrets` (the Worker must already be deployed).
import { CloudflareClient, putSecrets } from "@suluk/cloudflare";
import { loadEnvFile, readPrivateKey } from "@suluk/env/node";
import { env } from "../src/env";

const NAME = "autotoolfactory";
const cfg = await loadEnvFile(); // decrypt .env → { KEY: value } (+ inject into process.env)
const apiToken = cfg.CLOUDFLARE_D1_TOKEN ?? cfg.CLOUDFLARE_API_TOKEN;
if (!apiToken) { console.error("✗ no CLOUDFLARE_API_TOKEN in the decrypted .env — run `bun run provision` first."); process.exit(1); }
const priv = readPrivateKey();
if (!priv) { console.error("✗ no private key (~/.suluk/settings.json / SULUK_PRIVATE_KEY) — run `bun run link-key`."); process.exit(1); }

const secrets: Record<string, string> = { SULUK_PRIVATE_KEY: priv };
for (const k of env.forSurface("cloudflare")) if (cfg[k] !== undefined && cfg[k] !== "") secrets[k] = cfg[k];

const cf = new CloudflareClient({ apiToken, accountId: cfg.CLOUDFLARE_ACCOUNT_ID });
const set = await putSecrets(cf, NAME, secrets);
console.log(`✓ synced ${set.length} secret(s) to the Worker "${NAME}"${set.length ? ": " + set.join(", ") : ""}.`);
