#!/usr/bin/env bun
// AUTO-GENERATED by @suluk/platform. Push the DECRYPTION key to the Worker (so src/index.ts's loadEnv decrypts the committed
// .env at runtime), and optionally each runtime secret directly. Run at deploy: `bun run sync-secrets` (needs a deployed
// Worker + a CF-authed wrangler; the private key comes from ~/.suluk/settings.json).
import { loadEnvFile, readPrivateKey } from "@suluk/env/node";
import { env } from "../src/env";

const put = async (name: string, value: string) => {
  const p = Bun.spawn(["bunx", "wrangler", "secret", "put", name], { stdin: "pipe", stdout: "inherit", stderr: "inherit" });
  p.stdin.write(value); await p.stdin.end();
  if ((await p.exited) !== 0) { console.error(`✗ failed to put ${name}`); process.exit(1); }
  console.log(`✓ ${name}`);
};

// 1. the DECRYPTION key — the Worker's loadEnv decrypts the committed .env with it (the primary runtime path).
const priv = readPrivateKey();
if (!priv) { console.error("✗ no private key (~/.suluk/settings.json / SULUK_PRIVATE_KEY) — run `bun run link-key`"); process.exit(1); }
await put("SULUK_PRIVATE_KEY", priv);

// 2. (optional, belt-and-suspenders) push each cloudflare-surfaced runtime secret directly too.
const values = await loadEnvFile(); // decrypt every value in .env into a { KEY: value } record
const names = env.forSurface("cloudflare").filter((k) => values[k] !== undefined && values[k] !== "");
if (!names.length) {
  console.log("✓ synced SULUK_PRIVATE_KEY (no cloudflare-surfaced runtime secrets set yet).");
  process.exit(0);
}
for (const name of names) {
  const proc = Bun.spawn(["wrangler", "secret", "put", name], { stdin: "pipe", stdout: "inherit", stderr: "inherit" });
  proc.stdin.write(values[name]);
  await proc.stdin.end();
  if ((await proc.exited) !== 0) { console.error(`✗ failed to put ${name}`); process.exit(1); }
  console.log(`✓ ${name}`);
}
console.log(`✓ synced ${names.length} secret(s) to the Worker.`);
