/**
 * handwritten.cf-agent.ts — SIDE (a) of the Stage-0 measurement: what a developer writes TODAY to build Cloudflare's
 * canonical chat agent (developers.cloudflare.com/agents/getting-started/build-a-chat-agent/), by hand, following the docs.
 *
 * This file is a faithful REFERENCE ARTIFACT, not compiled here (it imports `agents`/`ai`/`zod`, not deps of this repo).
 * Every logical block is tagged with one of:
 *   [WIRING]          — identical for every agent; a generator could emit it verbatim from the contract.
 *   [TOOL-DERIVABLE]  — the tool's name/description/input-schema/dispatch; derivable from a contract operation.
 *   [BESPOKE]         — irreducible hand-written brain (loop policy, prompt text, side-effect bodies, client-only tools).
 *   [BESPOKE:GAP]     — bespoke TODAY, but a named Suluk facet would make it derivable (e.g. Stage-1.4 x-suluk-approval).
 *
 * The tags drive RESULT.md's line accounting. measure.ts (side b) proves every [WIRING]/[TOOL-DERIVABLE] tag by showing
 * the same value coming out of the real @suluk/agents projection.
 */

// [WIRING] imports — same for every Cloudflare agent
import { AIChatAgent } from "agents/ai-chat-agent";
import { routeAgentRequest } from "agents";
import { streamText, tool, stepCountIs, convertToModelMessages } from "ai";
import { createWorkersAI } from "workers-ai-provider";
import { z } from "zod";

// [WIRING] the Env shape (generated by `npx wrangler types` from wrangler.jsonc bindings)
interface Env {
  AI: Ai;
  WeatherAssistant: DurableObjectNamespace;
}

export class WeatherAssistant extends AIChatAgent<Env> {
  // [WIRING] the model loop entrypoint — same skeleton for every chat agent
  async onChatMessage() {
    const workersai = createWorkersAI({ binding: this.env.AI });

    const result = streamText({
      // [TOOL-DERIVABLE] model id — from the contract skill's `model[0]`
      model: workersai("@cf/meta/llama-3.3-70b-instruct"),
      // [BESPOKE] the system prompt TEXT (Suluk pins it by hash/version, but the bytes are authored)
      system:
        "You are a helpful assistant. You can check the weather with get_weather and evaluate arithmetic " +
        "with calculate. When the user asks for a calculation, call calculate and report the result. Be concise.",
      // [WIRING] message conversion + pruning — same every time
      messages: convertToModelMessages(this.messages),
      // [BESPOKE] loop policy — how many tool hops this agent may take
      stopWhen: stepCountIs(5),
      tools: {
        // [TOOL-DERIVABLE] name, description, input schema — all in the contract op getWeather
        get_weather: tool({
          description: "Look up the current weather for a city.",
          inputSchema: z.object({ city: z.string().max(80) }),
          // [BESPOKE] the side-effect BODY — what the tool actually does (Suluk dispatches to the operation; the
          // operation's implementation lives in the app, not the contract)
          execute: async ({ city }) => {
            const res = await fetch(`https://api.weather.example.com/now?city=${encodeURIComponent(city)}`);
            return await res.json();
          },
        }),
        // [TOOL-DERIVABLE] name, description, input schema — from the contract op calculate
        calculate: tool({
          description: "Evaluate an arithmetic expression and return the result.",
          inputSchema: z.object({ expression: z.string().max(256) }),
          // [BESPOKE:GAP] the approval gate — Stage-1.4 x-suluk-approval would make this predicate derivable
          needsApproval: async () => true,
          // [BESPOKE] the side-effect body
          execute: async ({ expression }) => ({ result: safeEval(expression) }),
        }),
        // [BESPOKE] a CLIENT-side tool (browser API) — not an HTTP operation, so not contract-derivable at all
        get_user_timezone: tool({
          description: "Get the user's local timezone.",
          inputSchema: z.object({}),
          // no execute → resolved on the client via the React onToolCall handler
        }),
      },
    });

    // [WIRING] stream the UI response — same every time
    return result.toUIMessageStreamResponse();
  }
}

// [BESPOKE] a real side-effect implementation the contract can't author
function safeEval(_expr: string): number {
  throw new Error("app-owned implementation");
}

// [WIRING] worker entrypoint — route to the agent, fall through to existing routes. Same every time.
export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    return (await routeAgentRequest(request, env)) ?? new Response("Not found", { status: 404 });
  },
};

/*
 * [WIRING] wrangler.jsonc the dev must hand-write (the part Stage-1.1/1.2 generate). Same shape every time:
 *
 * {
 *   "name": "weather-assistant",
 *   "main": "src/index.ts",
 *   "compatibility_date": "2026-06-01",
 *   "compatibility_flags": ["nodejs_compat"],
 *   "durable_objects": { "bindings": [{ "name": "WeatherAssistant", "class_name": "WeatherAssistant" }] },
 *   "migrations": [{ "tag": "v1", "new_sqlite_classes": ["WeatherAssistant"] }],
 *   "ai": { "binding": "AI" }
 * }
 */
