// AUTO-GENERATED by @suluk/platform — purge STATE. RECOMMENDED whenever you swap a mock provider for real keys (or
// vice-versa) or migrate the provision (a new service ⇒ new tables/KV/R2): the single environment is mock-until-keyed, so
// the old state's shape may not match the new one. Always clears LOCAL mock state; `--yes` also purges LIVE D1 + KV.
import { rmSync } from "node:fs";
import { discoverTableNames } from "@suluk/cloudflare/local";
import { loadEnvFile } from "@suluk/env/node";
import { CloudflareClient, queryD1, kvList, kvDelete } from "@suluk/cloudflare";

const yes = process.argv.includes("--yes");

// 1) LOCAL mock state — dev-only files; recreated on the next `bun run dev`. Always safe.
for (const f of [".suluk/dev.sqlite",".suluk/dev.sqlite-wal",".suluk/dev.sqlite-shm",".suluk/dev-kv.json",".suluk/dev-mailbox.json"]) { try { rmSync(f, { force: true }); } catch {} }
console.log("✓ purged local mock state (.suluk/*)");

// 2) LIVE state (if provisioned): DROP the app's D1 tables + clear the KV namespace. DESTRUCTIVE — needs `--yes`.
let S: Record<string, string | undefined> = { ...process.env };
try { S = { ...process.env, ...(await loadEnvFile()) }; } catch {}
const token = S.CLOUDFLARE_D1_TOKEN ?? S.CLOUDFLARE_API_TOKEN;
const account = S.CLOUDFLARE_ACCOUNT_ID;
const wrangler = await Bun.file("wrangler.toml").text().catch(() => "");
const d1Id = wrangler.match(/database_id\s*=\s*"([^"]+)"/)?.[1];
const kvId = wrangler.match(/\[\[kv_namespaces\]\][\s\S]*?\bid\s*=\s*"([^"]+)"/)?.[1];

if (token && account && d1Id) {
  if (!yes) {
    console.log(`\n⚠ LIVE state detected (D1 ${d1Id}${kvId ? " + KV " + kvId : ""}). Re-run \`bun run purge -- --yes\` to DROP all app tables + clear KV, then \`bun run provision\` to recreate the schema.`);
  } else {
    const cf = new CloudflareClient({ apiToken: token, accountId: account });
    for (const t of await discoverTableNames()) { await queryD1(cf, d1Id, `DROP TABLE IF EXISTS "${t}"`); console.log(`  dropped ${t}`); }
    if (kvId) {
      const kvCf = new CloudflareClient({ apiToken: (S.CLOUDFLARE_KV_TOKEN ?? token) as string, accountId: account });
      const keys = await kvList(kvCf, kvId);
      for (const k of keys) await kvDelete(kvCf, kvId, k);
      console.log(`  cleared ${keys.length} live KV keys`);
    }
    console.log("✓ purged LIVE state — run `bun run provision` to recreate the schema. (R2 objects, if any, purge via the CF dashboard.)");
  }
}
