// AUTO-GENERATED by @suluk/platform — the bun dev server. Runs the wired app under bun so `bun run dev` works with
// ZERO Cloudflare account and no wrangler. SINGLE ENVIRONMENT, MOCK-UNTIL-KEYED, per-layer + per-provider:
//  • STATE (D1+KV): once PROVISIONED (CF token + account + binding ids) it attaches to the SAME LIVE services as the Worker
//    over the Cloudflare HTTP API; a fresh app uses a local bun:sqlite + JSON-file mock. Both-or-neither (never split state).
//  • PROVIDERS (Google/Stripe/Resend): each real when ITS key is present, else its module's mock — INDEPENDENT of the state
//    layer, so a mock login/payment/email works against LIVE D1/KV too. RECOMMEND `bun run purge` when you swap a mock for a
//    real key (or vice-versa) or migrate the provision — the old state's shape may not match.
// NOTE: src/index.ts (the deployed Worker) imports NONE of this — bun:sqlite/mocks never enter the Worker bundle.
import { app } from "./index";
import { Database } from "bun:sqlite";
import { d1FromSqlite, jsonFileKvStore, jsonFileMailbox, applyLocalSchema } from "@suluk/cloudflare/local";
import { d1FromHttp, httpKvStore } from "@suluk/cloudflare/live";
import { CloudflareClient } from "@suluk/cloudflare";
import { mockStripeFetch } from "@suluk/billing";
import { loadEnvFile } from "@suluk/env/node";
import { mkdirSync } from "node:fs";
import { dirname } from "node:path";

const DB_PATH = process.env.SULUK_DB_PATH ?? ".suluk/dev.sqlite";
const KV_PATH = process.env.SULUK_KV_PATH ?? ".suluk/dev-kv.json";
const MAILBOX_PATH = process.env.SULUK_MAILBOX_PATH ?? ".suluk/dev-mailbox.json";
mkdirSync(dirname(DB_PATH), { recursive: true }); // ensure the local-state dir exists BEFORE bun:sqlite opens the DB (a fresh app has no .suluk/)
const PORT = Number(process.env.PORT ?? 8787);
const mailbox = jsonFileMailbox(MAILBOX_PATH); // a local inbox the mock email provider saves to

// Real secrets (if this app has been provisioned): decrypt the committed .env with the local private key. Fresh app / no
// key → {} → every provider mocks. Best-effort: a decryption failure never blocks the mock path.
let secrets: Record<string, string> = {};
try { secrets = await loadEnvFile(); } catch {}
const S = { ...process.env, ...secrets } as Record<string, string | undefined>; // resolved config (env + decrypted secrets)

// STATE layer: attach LIVE (same D1+KV as the Worker, over the CF HTTP API) once the minted token + account + the
// provisioned binding id(s) are present; else the local mock. Both-or-neither.
const cfToken = S.CLOUDFLARE_D1_TOKEN ?? S.CLOUDFLARE_API_TOKEN;
const cfAccount = S.CLOUDFLARE_ACCOUNT_ID;
const wrangler = await Bun.file("wrangler.toml").text().catch(() => "");
const d1Id = wrangler.match(/database_id\s*=\s*"([^"]+)"/)?.[1];
const kvId = wrangler.match(/\[\[kv_namespaces\]\][\s\S]*?\bid\s*=\s*"([^"]+)"/)?.[1];
const liveAttach = !!(cfToken && cfAccount && d1Id && kvId);

let DB: unknown;
let RATE_CREDIT_KV: unknown;
if (liveAttach) {
  const cf = new CloudflareClient({ apiToken: cfToken!, accountId: cfAccount! });
  DB = d1FromHttp(cf, d1Id!);
  RATE_CREDIT_KV = httpKvStore(new CloudflareClient({ apiToken: (S.CLOUDFLARE_KV_TOKEN ?? cfToken) as string, accountId: cfAccount! }), kvId!);
  console.log(`[suluk dev] LIVE-ATTACHED — same D1+KV as the Worker (${d1Id}); local changes hit production state.`);
} else {
  const sqlite = new Database(DB_PATH, { create: true });
  const tables = await applyLocalSchema(sqlite); // discover src/db/*.ts + create the tables from the drizzle schema
  DB = d1FromSqlite(sqlite);
  RATE_CREDIT_KV = jsonFileKvStore(KV_PATH);
  console.log(`[suluk dev] mock state — sqlite ${DB_PATH} (${tables.length} tables)`);
}

const env: Record<string, unknown> = {
  ...S,
  // `bun dev` IS the development server: force a non-production ENVIRONMENT so the mock-until-keyed providers ARM (dev-login,
  // console email, …) regardless of any deploy-time ENVIRONMENT=production that leaked in from .env/process.env. The deployed
  // Worker (src/index.ts) reads ENVIRONMENT from wrangler [vars]=production, untouched by this. Use `dev:cf`/`deploy` for prod.
  ENVIRONMENT: "development",
  DB,
  RATE_CREDIT_KV,
  SULUK_MAILBOX_SINK: mailbox,
};

const mocked = ["GOOGLE_CLIENT_ID", "STRIPE_SECRET_KEY", "RESEND_API_KEY"].filter((k) => !env[k]);
if (mocked.length) console.log(`[suluk dev] mocked providers (no key): ${mocked.join(", ")}${liveAttach ? " — against LIVE state; run \`bun run purge\` after swapping a mock for real keys" : ""}`);
if (!env.STRIPE_SECRET_KEY) { env.STRIPE_SECRET_KEY = "sk_mock_local"; env.STRIPE_FETCH = mockStripeFetch(); }

// a dev-only inbox view of the emails the mock provider captured (never mounted on the deployed Worker).
app.get("/api/email/dev/mailbox", async (c) => c.json(await mailbox.list()));

const ctx = { waitUntil() {}, passThroughOnException() {} } as unknown as ExecutionContext;
Bun.serve({ port: PORT, idleTimeout: 120, fetch: (req) => app.fetch(req, env as Parameters<typeof app.fetch>[1], ctx) });
console.log(`[suluk dev] → http://localhost:${PORT}  (mock-until-keyed; provision to go live)`);
