// AUTO-GENERATED by @suluk/platform — the bun MOCK-PROVIDER dev server. Runs the wired app under bun with a
// bun:sqlite DB + JSON-file KV, so `bun run dev` works with ZERO Cloudflare account and no wrangler. A provider goes REAL
// the moment its key is present (mock-until-keyed): add real keys to .env.temp + `bun run provision` and this file uses
// them. NOTE: src/index.ts (the deployed Worker) imports NONE of these mocks — bun:sqlite never enters the Worker bundle.
import { app } from "./index";
import { Database } from "bun:sqlite";
import { d1FromSqlite, jsonFileKvStore, applyLocalSchema } from "@suluk/cloudflare/local";
import { loadEnvFile } from "@suluk/env/node";

const DB_PATH = process.env.SULUK_DB_PATH ?? ".suluk/dev.sqlite";
const KV_PATH = process.env.SULUK_KV_PATH ?? ".suluk/dev-kv.json";
const PORT = Number(process.env.PORT ?? 8787);

const sqlite = new Database(DB_PATH, { create: true });
const tables = await applyLocalSchema(sqlite); // discover src/db/*.ts + create the tables from the drizzle schema
console.log(`[suluk dev] sqlite ${DB_PATH} — ${tables.length} tables`);

// Real secrets (if this app has been provisioned): decrypt the committed .env with the local private key. Fresh app / no
// key → {} → every provider mocks. Best-effort: a decryption failure never blocks the mock path.
let secrets: Record<string, string> = {};
try { secrets = await loadEnvFile(); } catch {}

// The request env: process.env < decrypted secrets < the mock bindings. DB/KV are always local (a bun process can't bind a
// remote D1/KV); the HTTP providers (Google/Stripe/Resend) use their real key when present, else their module's mock.
const env: Record<string, unknown> = {
  ...process.env,
  ...secrets,
  DB: d1FromSqlite(sqlite),
  RATE_CREDIT_KV: jsonFileKvStore(KV_PATH),
};

const mocked = ["GOOGLE_CLIENT_ID", "STRIPE_SECRET_KEY", "RESEND_API_KEY"].filter((k) => !env[k]);
if (mocked.length) console.log(`[suluk dev] mocked (no key): ${mocked.join(", ")}`);

const ctx = { waitUntil() {}, passThroughOnException() {} } as unknown as ExecutionContext;
Bun.serve({ port: PORT, idleTimeout: 120, fetch: (req) => app.fetch(req, env as Parameters<typeof app.fetch>[1], ctx) });
console.log(`[suluk dev] → http://localhost:${PORT}  (mock-until-keyed; provision to go live)`);
