// AUTO-GENERATED by @suluk/platform from platform.config.ts — the wired Hono entry. Edit freely.
import { createApp } from "./app";
import { loadEnv } from "@suluk/env";
// @ts-ignore — the committed, @suluk/env-encrypted .env, bundled as text (bun + wrangler text import).
import envText from "../.env" with { type: "text" };
import { mountAuthRoutes } from "./auth";
import { mountContract } from "./routes/contract";
import { mountMcp } from "./routes/mcp";
import { mountRateLimit } from "./services/rate-limit";
import { mountRateCredit } from "./services/rate-credit";
import { mountI18n } from "./services/i18n";
import { creditsRoutes } from "./routes/credits";
import { keysRoutes } from "./routes/keys";
import { billingRoutes } from "./routes/billing";
import { costRoutes } from "./routes/cost";
import { erasureRoutes } from "./routes/erasure";
import { emailRoutes } from "./routes/email";
import { webhooksRoutes } from "./routes/webhooks";
import { logsRoutes } from "./routes/logs";
import { referenceRoutes } from "./routes/reference";
import { adminRoutes } from "./routes/admin";

export const app = createApp();
mountAuthRoutes(app, {"mcp":{"loginPage":"https://autotoolfactory.example/oauth/sign-in","consentPage":"https://autotoolfactory.example/oauth/consent","resource":"https://autotoolfactory.example/api/mcp","scopes":["credits:read","credits:write","keys:read","keys:write","billing:read","billing:write","cost:read","logs:read"]}});
mountContract(app);
mountMcp(app);
mountRateLimit(app);
mountRateCredit(app);
mountI18n(app);
app.route("/api/credits", creditsRoutes());
app.route("/api/keys", keysRoutes());
app.route("/api/billing", billingRoutes());
app.route("/api/cost", costRoutes());
app.route("/api/erasure", erasureRoutes());
app.route("/api/email", emailRoutes());
app.route("/api/webhooks", webhooksRoutes());
app.route("/api/logs", logsRoutes());
app.route("/api/reference", referenceRoutes());
app.route("/api/admin", adminRoutes());

let secrets: Record<string, string> | null = null;
export default {
  async fetch(request: Request, env: Record<string, unknown>, ctx: ExecutionContext): Promise<Response> {
    if (!secrets && typeof env.SULUK_PRIVATE_KEY === "string") secrets = await loadEnv({ content: envText, privateKey: env.SULUK_PRIVATE_KEY });
    const merged = secrets ? { ...secrets, ...env } : env;
    return app.fetch(request, merged as Parameters<typeof app.fetch>[1], ctx);
  },
};
